USE [master]
GO

CREATE DATABASE [PEMS_RBAC_DATABASE_NAME]
 ON  PRIMARY 
( NAME = N'PEMS_RBAC_LOGICAL_NAME', FILENAME = N'PEMS_RBAC_DATABASE_PATH\PEMS_RBAC_FILE_NAME.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'PEMS_RBAC_LOGICAL_NAME_log', FILENAME = N'PEMS_RBAC_DATABASE_PATH\PEMS_RBAC_FILE_NAME.ldf' , SIZE = 35712KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [PEMS_RBAC_DATABASE_NAME] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PEMS_RBAC_DATABASE_NAME].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [PEMS_RBAC_DATABASE_NAME] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [PEMS_RBAC_DATABASE_NAME] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [PEMS_RBAC_DATABASE_NAME] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [PEMS_RBAC_DATABASE_NAME] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [PEMS_RBAC_DATABASE_NAME] SET ARITHABORT OFF 
GO

ALTER DATABASE [PEMS_RBAC_DATABASE_NAME] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [PEMS_RBAC_DATABASE_NAME] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [PEMS_RBAC_DATABASE_NAME] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [PEMS_RBAC_DATABASE_NAME] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [PEMS_RBAC_DATABASE_NAME] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [PEMS_RBAC_DATABASE_NAME] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [PEMS_RBAC_DATABASE_NAME] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [PEMS_RBAC_DATABASE_NAME] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [PEMS_RBAC_DATABASE_NAME] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [PEMS_RBAC_DATABASE_NAME] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [PEMS_RBAC_DATABASE_NAME] SET  DISABLE_BROKER 
GO

ALTER DATABASE [PEMS_RBAC_DATABASE_NAME] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [PEMS_RBAC_DATABASE_NAME] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [PEMS_RBAC_DATABASE_NAME] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [PEMS_RBAC_DATABASE_NAME] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [PEMS_RBAC_DATABASE_NAME] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [PEMS_RBAC_DATABASE_NAME] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [PEMS_RBAC_DATABASE_NAME] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [PEMS_RBAC_DATABASE_NAME] SET RECOVERY FULL 
GO

ALTER DATABASE [PEMS_RBAC_DATABASE_NAME] SET  MULTI_USER 
GO

ALTER DATABASE [PEMS_RBAC_DATABASE_NAME] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [PEMS_RBAC_DATABASE_NAME] SET DB_CHAINING OFF 
GO

ALTER DATABASE [PEMS_RBAC_DATABASE_NAME] SET  READ_WRITE 
GO

