//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class AI_OFFICERS
    {
        public AI_OFFICERS()
        {
            this.AI_ACTIVITYLOG = new HashSet<AI_ACTIVITYLOG>();
            this.AI_PARK_NOTE = new HashSet<AI_PARK_NOTE>();
            this.AI_PARKING = new HashSet<AI_PARKING>();
            this.AI_PARKING_TRANSLINK = new HashSet<AI_PARKING_TRANSLINK>();
        }
    
        public int OfficerId { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string OfficerName { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public int ActivityStatus { get; set; }
    
        public virtual ICollection<AI_ACTIVITYLOG> AI_ACTIVITYLOG { get; set; }
        public virtual AssetState AssetState { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual ICollection<AI_PARK_NOTE> AI_PARK_NOTE { get; set; }
        public virtual ICollection<AI_PARKING> AI_PARKING { get; set; }
        public virtual ICollection<AI_PARKING_TRANSLINK> AI_PARKING_TRANSLINK { get; set; }
    }
}
