//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class AI_PARKING_VIOS
    {
        public int ParkingViosId { get; set; }
        public int ParkingId { get; set; }
        public int CustomerID { get; set; }
        public Nullable<int> OccurNo { get; set; }
        public string VioCode { get; set; }
        public string VioXferCode { get; set; }
        public string VioDescription1 { get; set; }
        public string VioDescription2 { get; set; }
        public Nullable<float> VioFine { get; set; }
        public Nullable<float> VioLateFee1 { get; set; }
        public Nullable<float> VioLateFee2 { get; set; }
        public Nullable<float> VioLateFee3 { get; set; }
        public string VioQueryType { get; set; }
        public string VioSelect { get; set; }
    
        public virtual AI_PARKING AI_PARKING { get; set; }
    }
}
