//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Area
    {
        public Area()
        {
            this.AreaSeqs = new HashSet<AreaSeq>();
            this.Meters = new HashSet<Meter>();
        }
    
        public Nullable<long> GlobalAreaID { get; set; }
        public int CustomerID { get; set; }
        public int AreaID { get; set; }
        public string AreaName { get; set; }
        public string Description { get; set; }
        public Nullable<int> AreaState { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ICollection<AreaSeq> AreaSeqs { get; set; }
        public virtual ICollection<Meter> Meters { get; set; }
    }
}
