//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetType
    {
        public int AssetTypeId { get; set; }
        public int MeterGroupId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<bool> IsDisplay { get; set; }
        public Nullable<int> SLAMinutes { get; set; }
        public string MeterGroupDesc { get; set; }
        public Nullable<int> PreventativeMaintenanceScheduleDays { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual MeterGroup MeterGroup { get; set; }
    }
}
