//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetPending
    {
        public long AssetPendingId { get; set; }
        public int CustomerId { get; set; }
        public int AreaId { get; set; }
        public int MeterId { get; set; }
        public int CreateUserId { get; set; }
        public System.DateTime RecordCreateDateTime { get; set; }
        public Nullable<System.DateTime> RecordMigrationDateTime { get; set; }
        public long AssetId { get; set; }
        public int AssetType { get; set; }
        public string AssetName { get; set; }
        public Nullable<int> AssetModel { get; set; }
        public Nullable<System.DateTime> NextPreventativeMaintenance { get; set; }
        public string Street { get; set; }
        public Nullable<int> OperationalStatus { get; set; }
        public Nullable<int> MeterMapAreaId2 { get; set; }
        public Nullable<int> MeterMapZoneId { get; set; }
        public Nullable<int> MeterMapSuburbId { get; set; }
        public Nullable<int> MeterMapCollectionRoute { get; set; }
        public Nullable<int> MeterMapMaintenanceRoute { get; set; }
        public Nullable<int> MeterMapSensorId { get; set; }
        public Nullable<int> MeterMapGatewayId { get; set; }
        public Nullable<int> MeterMapCashBoxId { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<int> SpaceCount { get; set; }
        public Nullable<int> DemandStatus { get; set; }
        public Nullable<System.DateTime> WarrantyExpiration { get; set; }
        public Nullable<int> SpaceType { get; set; }
        public Nullable<long> AssociatedMeterId { get; set; }
        public Nullable<long> AssocidateSpaceId { get; set; }
        public Nullable<System.DateTime> DateInstalled { get; set; }
        public string AssetFirmwareVersion { get; set; }
        public string AssetSoftwareVersion { get; set; }
        public string MPVFirmware { get; set; }
        public Nullable<int> GatewayModel { get; set; }
        public string Manufacturer { get; set; }
        public string HardwareVeresion { get; set; }
        public Nullable<int> PowerSource { get; set; }
        public Nullable<long> PrimaryGateway { get; set; }
        public Nullable<long> SecondaryGateway { get; set; }
        public string LocationGateway { get; set; }
        public string LocationMeters { get; set; }
        public string LocationSensors { get; set; }
        public Nullable<System.DateTime> LastPreventativeMaintenance { get; set; }
        public Nullable<int> AssetState { get; set; }
        public Nullable<int> AssociatedMeterAreaId { get; set; }
        public Nullable<System.DateTime> OperationalStatusTime { get; set; }
        public Nullable<int> CashboxLocationId { get; set; }
        public Nullable<int> AssetPendingReasonId { get; set; }
        public string DisplaySpaceNum { get; set; }
        public Nullable<System.DateTime> MigratedTs { get; set; }
        public string ErrorMessage { get; set; }
        public Nullable<int> MeterMapMechId { get; set; }
        public Nullable<int> MeterMapDataKeyId { get; set; }
        public string MechSerialNumber { get; set; }
        public Nullable<int> MeterMapHousingId { get; set; }
        public string CSParkSerial { get; set; }
        public Nullable<int> MeterMapCSParkId { get; set; }
    
        public virtual AssetPendingReason AssetPendingReason { get; set; }
    }
}
