//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetState
    {
        public AssetState()
        {
            this.AssetStateCustomers = new HashSet<AssetStateCustomer>();
            this.CashBoxes = new HashSet<CashBox>();
            this.DiscountSchemeCustomers = new HashSet<DiscountSchemeCustomer>();
            this.Gateways = new HashSet<Gateway>();
            this.Meters = new HashSet<Meter>();
            this.ParkingSpaces = new HashSet<ParkingSpace>();
            this.SensorMappings = new HashSet<SensorMapping>();
            this.Sensors = new HashSet<Sensor>();
            this.AI_OFFICERS = new HashSet<AI_OFFICERS>();
        }
    
        public int AssetStateId { get; set; }
        public string AssetStateDesc { get; set; }
    
        public virtual ICollection<AssetStateCustomer> AssetStateCustomers { get; set; }
        public virtual ICollection<CashBox> CashBoxes { get; set; }
        public virtual ICollection<DiscountSchemeCustomer> DiscountSchemeCustomers { get; set; }
        public virtual ICollection<Gateway> Gateways { get; set; }
        public virtual ICollection<Meter> Meters { get; set; }
        public virtual ICollection<ParkingSpace> ParkingSpaces { get; set; }
        public virtual ICollection<SensorMapping> SensorMappings { get; set; }
        public virtual ICollection<Sensor> Sensors { get; set; }
        public virtual ICollection<AI_OFFICERS> AI_OFFICERS { get; set; }
    }
}
