//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlackListArchive
    {
        public string XCardNum { get; set; }
        public Nullable<int> Code { get; set; }
        public Nullable<bool> Action { get; set; }
        public System.DateTime DateTimeAction { get; set; }
        public Nullable<int> UserID { get; set; }
    }
}
