//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class CardType
    {
        public CardType()
        {
            this.OLTEventDetails = new HashSet<OLTEventDetail>();
            this.TransactionsAudits = new HashSet<TransactionsAudit>();
            this.TransactionsPendings = new HashSet<TransactionsPending>();
            this.TransactionsReconciles = new HashSet<TransactionsReconcile>();
            this.OLTAcquirers = new HashSet<OLTAcquirer>();
        }
    
        public int CardTypeCode { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<OLTEventDetail> OLTEventDetails { get; set; }
        public virtual ICollection<TransactionsAudit> TransactionsAudits { get; set; }
        public virtual ICollection<TransactionsPending> TransactionsPendings { get; set; }
        public virtual ICollection<TransactionsReconcile> TransactionsReconciles { get; set; }
        public virtual ICollection<OLTAcquirer> OLTAcquirers { get; set; }
    }
}
