//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashBoxLocationType
    {
        public CashBoxLocationType()
        {
            this.CashBoxes = new HashSet<CashBox>();
        }
    
        public int CashBoxLocationTypeId { get; set; }
        public string CashBoxLocationTypeDesc { get; set; }
    
        public virtual ICollection<CashBox> CashBoxes { get; set; }
    }
}
