//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashBox
    {
        public int CashBoxID { get; set; }
        public int CustomerID { get; set; }
        public int CashBoxSeq { get; set; }
        public int CashBoxState { get; set; }
        public Nullable<System.DateTime> InstallDate { get; set; }
        public Nullable<int> CashBoxModel { get; set; }
        public Nullable<int> CashBoxType { get; set; }
        public Nullable<int> OperationalStatus { get; set; }
        public Nullable<System.DateTime> OperationalStatusTime { get; set; }
        public Nullable<System.DateTime> LastPreventativeMaintenance { get; set; }
        public Nullable<System.DateTime> NextPreventativeMaintenance { get; set; }
        public string CashBoxName { get; set; }
        public Nullable<System.DateTime> WarrantyExpiration { get; set; }
        public Nullable<int> CashBoxLocationTypeId { get; set; }
        public Nullable<System.DateTime> OperationalStatusEndTime { get; set; }
        public string OperationalStatusComment { get; set; }
    
        public virtual AssetState AssetState { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual CashBoxLocationType CashBoxLocationType { get; set; }
        public virtual MechanismMaster MechanismMaster { get; set; }
        public virtual MeterGroup MeterGroup { get; set; }
        public virtual OperationalStatu OperationalStatu { get; set; }
    }
}
