//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashBoxDataImport
    {
        public Nullable<long> GlobalMeterId { get; set; }
        public int CustomerId { get; set; }
        public int AreaId { get; set; }
        public int MeterId { get; set; }
        public System.DateTime DateTimeIns { get; set; }
        public string CashBoxId { get; set; }
        public int CashboxSequenceNo { get; set; }
        public System.DateTime DateTimeRead { get; set; }
        public Nullable<System.DateTime> DateTimeRem { get; set; }
        public string OperatorId { get; set; }
        public string AutoFlag { get; set; }
        public Nullable<int> Dollar2Coins { get; set; }
        public Nullable<int> Dollar1Coins { get; set; }
        public Nullable<int> Cents50Coins { get; set; }
        public Nullable<int> Cents20Coins { get; set; }
        public Nullable<int> Cents10Coins { get; set; }
        public Nullable<int> Cents5Coins { get; set; }
        public Nullable<double> AmtCashless { get; set; }
        public Nullable<double> AmtAuto { get; set; }
        public Nullable<double> AmtManual { get; set; }
        public Nullable<float> AmtDiff { get; set; }
        public Nullable<double> PercentFull { get; set; }
        public string MeterStatus { get; set; }
        public Nullable<int> TallyRejects { get; set; }
        public Nullable<int> CreditCounter { get; set; }
        public Nullable<long> TimeActive { get; set; }
        public Nullable<float> MinVolts { get; set; }
        public Nullable<float> MaxTemp { get; set; }
        public Nullable<int> FirmwareVer { get; set; }
        public Nullable<int> FirmwareRev { get; set; }
        public Nullable<int> EventCode { get; set; }
        public string FileName { get; set; }
        public Nullable<long> FileProcessId { get; set; }
        public Nullable<long> EventUID { get; set; }
        public Nullable<long> CollectionRunId { get; set; }
        public bool UnscheduledFlag { get; set; }
        public Nullable<int> Coin1Cnt { get; set; }
        public Nullable<int> Coin2Cnt { get; set; }
        public Nullable<int> Coin3Cnt { get; set; }
        public Nullable<int> Coin4Cnt { get; set; }
        public Nullable<int> Coin5Cnt { get; set; }
        public Nullable<int> Coin6Cnt { get; set; }
        public Nullable<int> Coin7Cnt { get; set; }
        public Nullable<int> Coin8Cnt { get; set; }
        public Nullable<int> Coin9Cnt { get; set; }
        public Nullable<int> Coin10Cnt { get; set; }
        public Nullable<int> Coin11Cnt { get; set; }
        public Nullable<int> Coin12Cnt { get; set; }
        public Nullable<int> Coin13Cnt { get; set; }
        public Nullable<int> Coin14Cnt { get; set; }
        public Nullable<int> Coin15Cnt { get; set; }
        public Nullable<int> Coin16Cnt { get; set; }
        public Nullable<int> Coin17Cnt { get; set; }
        public Nullable<int> Coin18Cnt { get; set; }
        public Nullable<int> Coin19Cnt { get; set; }
        public Nullable<int> Coin20Cnt { get; set; }
        public Nullable<int> Coin21Cnt { get; set; }
        public Nullable<int> Coin22Cnt { get; set; }
        public Nullable<int> Coin23Cnt { get; set; }
        public Nullable<int> Coin24Cnt { get; set; }
        public Nullable<int> Coin25Cnt { get; set; }
        public Nullable<int> Coin26Cnt { get; set; }
        public Nullable<int> Coin27Cnt { get; set; }
        public Nullable<int> Coin28Cnt { get; set; }
        public Nullable<int> Coin29Cnt { get; set; }
        public Nullable<int> Coin30Cnt { get; set; }
    }
}
