//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoinDenomination
    {
        public CoinDenomination()
        {
            this.CoinDenominationCustomers = new HashSet<CoinDenominationCustomer>();
        }
    
        public int CoinDenominationId { get; set; }
        public string CountryCode { get; set; }
        public int CoinValue { get; set; }
        public string CoinName { get; set; }
        public string TransactionsCashMap { get; set; }
        public string CashBoxDataImportMap { get; set; }
    
        public virtual ICollection<CoinDenominationCustomer> CoinDenominationCustomers { get; set; }
    }
}
