//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class CollRouteSeq
    {
        public int CollRouteId { get; set; }
        public int CollSeq { get; set; }
        public double Latitude { get; set; }
        public double Longitude { get; set; }
    
        public virtual CollRoute CollRoute { get; set; }
    }
}
