//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class CollDataImport
    {
        public Nullable<long> GlobalMeterId { get; set; }
        public int CustomerId { get; set; }
        public int AreaId { get; set; }
        public int MeterId { get; set; }
        public System.DateTime DateTimeRem { get; set; }
        public string OldCBBarCode { get; set; }
        public string NewCBBarCode { get; set; }
        public string StatusCode { get; set; }
        public int AmountInCents { get; set; }
        public string CashBoxId { get; set; }
        public string Collector { get; set; }
        public string FileNameImp { get; set; }
        public System.DateTime DateTimeImp { get; set; }
    
        public virtual Meter Meter { get; set; }
    }
}
