//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class CollectionRunStatu
    {
        public CollectionRunStatu()
        {
            this.CollectionRuns = new HashSet<CollectionRun>();
        }
    
        public int CollectionRunStatusId { get; set; }
        public string CollectionRunStatusDesc { get; set; }
    
        public virtual ICollection<CollectionRun> CollectionRuns { get; set; }
    }
}
