//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class CollReconDetCBRCOMMSsubV
    {
        public Nullable<int> xFileProcessID { get; set; }
        public int CustomerId { get; set; }
        public int AreaId { get; set; }
        public int MeterId { get; set; }
        public string MeterName { get; set; }
        public string Street { get; set; }
        public string Area { get; set; }
        public string Zone { get; set; }
        public string Suburb { get; set; }
        public string DemandArea { get; set; }
        public Nullable<long> EventUID { get; set; }
        public string CashBoxId { get; set; }
        public System.DateTime CashBoxReadTime { get; set; }
        public Nullable<long> CollectionRunId { get; set; }
        public bool UnscheduledFlag { get; set; }
        public string OldCashBoxID { get; set; }
        public int CashboxSequenceNo { get; set; }
        public Nullable<int> seqNumComms { get; set; }
        public System.DateTime InsertionTimeCBR { get; set; }
        public Nullable<System.DateTime> RemovalTimeCBR { get; set; }
        public Nullable<System.DateTime> CollectionDateTime { get; set; }
        public string OperatorId { get; set; }
        public Nullable<double> MeterReportedAmount { get; set; }
        public Nullable<double> CashboxChipAmount { get; set; }
        public Nullable<double> VendorReportedAmount { get; set; }
        public Nullable<float> DiffVendorChip { get; set; }
        public Nullable<double> DiffMeterChip { get; set; }
        public Nullable<double> DiffMeterVendor { get; set; }
        public Nullable<double> PercentFull { get; set; }
        public Nullable<double> AvgL10 { get; set; }
        public Nullable<double> StdDevL10 { get; set; }
        public Nullable<double> Var_L10 { get; set; }
        public string CollectionFilename { get; set; }
    }
}
