//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class CollectionRunReport
    {
        public CollectionRunReport()
        {
            this.AuditRegistries = new HashSet<AuditRegistry>();
            this.Transactions = new HashSet<Transaction>();
        }
    
        public long CollectionRunReportId { get; set; }
        public int CustomerId { get; set; }
        public long CollectionRunId { get; set; }
        public System.DateTime CollectionDate { get; set; }
        public Nullable<int> MeterCoinType1Count { get; set; }
        public Nullable<int> MeterCoinType2Count { get; set; }
        public Nullable<int> MeterCoinType3Count { get; set; }
        public Nullable<int> MeterCoinType4Count { get; set; }
        public Nullable<int> MeterCoinType5Count { get; set; }
        public Nullable<int> MeterCoinType6Count { get; set; }
        public Nullable<int> MeterCoinType7Count { get; set; }
        public Nullable<int> MeterCoinType8Count { get; set; }
        public int TotalMeterCount { get; set; }
        public Nullable<int> ManualCoinType1Count { get; set; }
        public Nullable<int> ManualCoinType2Count { get; set; }
        public Nullable<int> ManualCoinType3Count { get; set; }
        public Nullable<int> ManualCoinType4Count { get; set; }
        public Nullable<int> ManualCoinType5Count { get; set; }
        public Nullable<int> ManualCoinType6Count { get; set; }
        public Nullable<int> ManualCoinType7Count { get; set; }
        public Nullable<int> ManualCoinType8Count { get; set; }
        public int TotalManualMeterCount { get; set; }
        public Nullable<System.DateTime> ProcessedTS { get; set; }
        public Nullable<int> VendorId { get; set; }
        public Nullable<int> TotalByChip { get; set; }
        public Nullable<int> ChipAutoCoinType1Count { get; set; }
        public Nullable<int> ChipAutoCoinType2Count { get; set; }
        public Nullable<int> ChipAutoCoinType3Count { get; set; }
        public Nullable<int> ChipAutoCoinType4Count { get; set; }
        public Nullable<int> ChipAutoCoinType5Count { get; set; }
        public Nullable<int> ChipAutoCoinType6Count { get; set; }
        public Nullable<int> ChipAutoCoinType7Count { get; set; }
        public Nullable<int> ChipAutoCoinType8Count { get; set; }
        public Nullable<int> TotalByChipMeterCount { get; set; }
        public Nullable<int> TotalByChipCoinCount { get; set; }
        public int TotalManualCoinCount { get; set; }
        public int TotalManualCashAmt { get; set; }
        public int TotalMeterCashAmt { get; set; }
        public int TotalMeterCoinCount { get; set; }
        public Nullable<int> MeterCoinType9Count { get; set; }
        public Nullable<int> MeterCoinType10Count { get; set; }
        public Nullable<int> MeterCoinType11Count { get; set; }
        public Nullable<int> MeterCoinType12Count { get; set; }
        public Nullable<int> MeterCoinType13Count { get; set; }
        public Nullable<int> MeterCoinType14Count { get; set; }
        public Nullable<int> MeterCoinType15Count { get; set; }
        public Nullable<int> MeterCoinType16Count { get; set; }
        public Nullable<int> MeterCoinType17Count { get; set; }
        public Nullable<int> MeterCoinType18Count { get; set; }
        public Nullable<int> MeterCoinType19Count { get; set; }
        public Nullable<int> MeterCoinType20Count { get; set; }
        public Nullable<int> MeterCoinType21Count { get; set; }
        public Nullable<int> MeterCoinType22Count { get; set; }
        public Nullable<int> MeterCoinType23Count { get; set; }
        public Nullable<int> MeterCoinType24Count { get; set; }
        public Nullable<int> MeterCoinType25Count { get; set; }
        public Nullable<int> MeterCoinType26Count { get; set; }
        public Nullable<int> MeterCoinType27Count { get; set; }
        public Nullable<int> MeterCoinType28Count { get; set; }
        public Nullable<int> MeterCoinType29Count { get; set; }
        public Nullable<int> MeterCoinType30Count { get; set; }
        public Nullable<int> ManualCoinType9Count { get; set; }
        public Nullable<int> ManualCoinType10Count { get; set; }
        public Nullable<int> ManualCoinType11Count { get; set; }
        public Nullable<int> ManualCoinType12Count { get; set; }
        public Nullable<int> ManualCoinType13Count { get; set; }
        public Nullable<int> ManualCoinType14Count { get; set; }
        public Nullable<int> ManualCoinType15Count { get; set; }
        public Nullable<int> ManualCoinType16Count { get; set; }
        public Nullable<int> ManualCoinType17Count { get; set; }
        public Nullable<int> ManualCoinType18Count { get; set; }
        public Nullable<int> ManualCoinType19Count { get; set; }
        public Nullable<int> ManualCoinType20Count { get; set; }
        public Nullable<int> ManualCoinType21Count { get; set; }
        public Nullable<int> ManualCoinType22Count { get; set; }
        public Nullable<int> ManualCoinType23Count { get; set; }
        public Nullable<int> ManualCoinType24Count { get; set; }
        public Nullable<int> ManualCoinType25Count { get; set; }
        public Nullable<int> ManualCoinType26Count { get; set; }
        public Nullable<int> ManualCoinType27Count { get; set; }
        public Nullable<int> ManualCoinType28Count { get; set; }
        public Nullable<int> ManualCoinType29Count { get; set; }
        public Nullable<int> ManualCoinType30Count { get; set; }
        public Nullable<int> ChipAutoCointType9Count { get; set; }
        public Nullable<int> ChipAutoCointType10Count { get; set; }
        public Nullable<int> ChipAutoCointType11Count { get; set; }
        public Nullable<int> ChipAutoCointType12Count { get; set; }
        public Nullable<int> ChipAutoCointType13Count { get; set; }
        public Nullable<int> ChipAutoCointType14Count { get; set; }
        public Nullable<int> ChipAutoCointType15Count { get; set; }
        public Nullable<int> ChipAutoCointType16Count { get; set; }
        public Nullable<int> ChipAutoCointType17Count { get; set; }
        public Nullable<int> ChipAutoCointType18Count { get; set; }
        public Nullable<int> ChipAutoCointType19Count { get; set; }
        public Nullable<int> ChipAutoCointType20Count { get; set; }
        public Nullable<int> ChipAutoCointType21Count { get; set; }
        public Nullable<int> ChipAutoCointType22Count { get; set; }
        public Nullable<int> ChipAutoCointType23Count { get; set; }
        public Nullable<int> ChipAutoCointType24Count { get; set; }
        public Nullable<int> ChipAutoCointType25Count { get; set; }
        public Nullable<int> ChipAutoCointType26Count { get; set; }
        public Nullable<int> ChipAutoCointType27Count { get; set; }
        public Nullable<int> ChipAutoCointType28Count { get; set; }
        public Nullable<int> ChipAutoCointType29Count { get; set; }
        public Nullable<int> ChipAutoCointType30Count { get; set; }
        public Nullable<long> MaxAmt_Meter { get; set; }
        public Nullable<long> MaxAmt_Chip { get; set; }
    
        public virtual ICollection<AuditRegistry> AuditRegistries { get; set; }
        public virtual ICollection<Transaction> Transactions { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual CollectionRun CollectionRun { get; set; }
    }
}
