//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class CollRouteManualAmount
    {
        public int Id { get; set; }
        public int CustomerID { get; set; }
        public int CollRouteId { get; set; }
        public System.DateTime CollTime { get; set; }
        public int AmoutInCent { get; set; }
        public Nullable<int> ManualCoinCountType1 { get; set; }
        public Nullable<int> ManualCoinCountType2 { get; set; }
        public Nullable<int> ManualCoinCountType3 { get; set; }
        public Nullable<int> ManualCoinCountType4 { get; set; }
        public Nullable<int> ManualCoinCountType5 { get; set; }
        public Nullable<int> ManualCoinCountType6 { get; set; }
        public Nullable<int> ManualCoinCountType7 { get; set; }
        public Nullable<int> ManualCoinCountType8 { get; set; }
        public Nullable<long> CollectionRunId { get; set; }
    
        public virtual CollRoute CollRoute { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
