//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class CollectionRunMeter
    {
        public long CollectionRunMeterId { get; set; }
        public long CollectionRunId { get; set; }
        public int CustomerId { get; set; }
        public int AreaId { get; set; }
        public int MeterId { get; set; }
        public string VendorId { get; set; }
        public Nullable<System.DateTime> ExipryDate { get; set; }
    
        public virtual Meter Meter { get; set; }
        public virtual CollectionRun CollectionRun { get; set; }
    }
}
