//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class CollectionRunSummary_View
    {
        public System.DateTime RemovalTimeSched { get; set; }
        public int SchedDays { get; set; }
        public System.DateTime CasBoxReadTime { get; set; }
        public System.DateTime CollectionRunDate { get; set; }
        public int CustomerID { get; set; }
        public int AreaID { get; set; }
        public int MeterId { get; set; }
        public Nullable<System.DateTime> OperationalStatusEndTime { get; set; }
        public double Amount { get; set; }
        public int CashboxChipAmount { get; set; }
        public string Collector { get; set; }
        public string CollectionFilename { get; set; }
        public string CashBoxId { get; set; }
        public Nullable<System.DateTime> OperationalStatusTime { get; set; }
        public Nullable<int> CashboxSequenceNo { get; set; }
        public Nullable<int> CollectorId { get; set; }
        public Nullable<System.DateTime> InsertionTimeCBR { get; set; }
        public Nullable<double> VendorReportedAmount { get; set; }
        public Nullable<double> MeterReportedAmount { get; set; }
        public Nullable<double> CashlessAmount { get; set; }
    }
}
