//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfigProfileSpace
    {
        public long ConfigProfileSpaceId { get; set; }
        public long ConfigProfileId { get; set; }
        public int CustomerId { get; set; }
        public long ParkingSpaceId { get; set; }
        public Nullable<System.DateTime> ScheduledDate { get; set; }
        public Nullable<System.DateTime> ActivationDate { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public System.DateTime CreateDatetime { get; set; }
        public Nullable<int> ConfigStatus { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual ConfigProfile ConfigProfile { get; set; }
        public virtual ParkingSpace ParkingSpace { get; set; }
        public virtual ConfigStatu ConfigStatu { get; set; }
    }
}
