//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfigurationIDGen
    {
        public long ConfigurationID { get; set; }
        public System.DateTime GenDate { get; set; }
    
        public virtual HolidayRateConfiguration HolidayRateConfiguration { get; set; }
        public virtual RateScheduleConfiguration RateScheduleConfiguration { get; set; }
        public virtual TariffRateConfiguration TariffRateConfiguration { get; set; }
    }
}
