//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditCardReconciliationV
    {
        public int CustomerID { get; set; }
        public long TransactionsCreditCardID { get; set; }
        public long TransAuditId { get; set; }
        public System.DateTime TransactionDateTime { get; set; }
        public Nullable<System.DateTime> TransactionAuditTime { get; set; }
        public long TransactionsID { get; set; }
        public string MeterName { get; set; }
        public int MeterID { get; set; }
        public Nullable<int> AreaID { get; set; }
        public Nullable<int> ZoneId { get; set; }
        public string Street { get; set; }
        public string Area { get; set; }
        public string Zone { get; set; }
        public string Suburb { get; set; }
        public string DemandArea { get; set; }
        public Nullable<long> SpaceId { get; set; }
        public int status { get; set; }
        public string PaymentStatusType { get; set; }
        public string BatchId { get; set; }
        public string CreditCardType { get; set; }
        public int ReceiptNo { get; set; }
        public Nullable<int> AmountPaidInCents { get; set; }
        public string TimePaid { get; set; }
        public Nullable<long> TransAcquirerID { get; set; }
        public string AcquirerTransReference { get; set; }
        public string AcquirerResponseDetail { get; set; }
        public Nullable<int> AcquirerResponseCode { get; set; }
        public string transType { get; set; }
        public string TimeType1 { get; set; }
        public string TimeType2 { get; set; }
        public string TimeType3 { get; set; }
        public string TimeType4 { get; set; }
        public string TimeType5 { get; set; }
    }
}
