//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditCardType
    {
        public CreditCardType()
        {
            this.CreditCardTypesCustomers = new HashSet<CreditCardTypesCustomer>();
            this.SupportedCreditCards = new HashSet<SupportedCreditCard>();
            this.Transactions = new HashSet<Transaction>();
            this.TransactionsCreditCards = new HashSet<TransactionsCreditCard>();
        }
    
        public int CreditCardType1 { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<CreditCardTypesCustomer> CreditCardTypesCustomers { get; set; }
        public virtual ICollection<SupportedCreditCard> SupportedCreditCards { get; set; }
        public virtual ICollection<Transaction> Transactions { get; set; }
        public virtual ICollection<TransactionsCreditCard> TransactionsCreditCards { get; set; }
    }
}
