//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class CSPark
    {
        public int CSParkId { get; set; }
        public string CSParkSerial { get; set; }
        public Nullable<int> CSParkType { get; set; }
        public Nullable<int> Customerid { get; set; }
        public string SimNo { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> InactiveRemarkID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public System.DateTime InsertedDate { get; set; }
        public string Notes { get; set; }
        public Nullable<int> CSParkIdNumber { get; set; }
        public int Id { get; set; }
    
        public virtual MechanismMaster MechanismMaster { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual InactiveRemark InactiveRemark { get; set; }
    }
}
