//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerPaymentTransactionV
    {
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> MeterId { get; set; }
        public Nullable<int> SensorID { get; set; }
        public string MeterName { get; set; }
        public string MeterType { get; set; }
        public string Suburb { get; set; }
        public Nullable<int> AreaId2 { get; set; }
        public Nullable<int> ZoneId { get; set; }
        public string Area { get; set; }
        public string Zone { get; set; }
        public string Street { get; set; }
        public Nullable<long> SpaceId { get; set; }
        public Nullable<int> BayId { get; set; }
        public string DemandArea { get; set; }
        public long SensorPaymentTransactionId { get; set; }
        public System.DateTime ArrivalTime { get; set; }
        public string VehicleStatus { get; set; }
        public Nullable<System.DateTime> DepartureTime { get; set; }
        public Nullable<long> TransactionsID { get; set; }
        public Nullable<System.DateTime> TimeOfTransaction { get; set; }
        public Nullable<System.DateTime> ExpirationTime { get; set; }
        public Nullable<System.DateTime> TimeProcessed { get; set; }
        public string PaymentMethod { get; set; }
        public Nullable<int> TimePaid { get; set; }
        public Nullable<System.DateTime> LastTimeProcessed { get; set; }
        public Nullable<System.DateTime> LastExpirationTime { get; set; }
        public Nullable<int> LastTxAmountInCent { get; set; }
        public Nullable<int> LastTimePaid { get; set; }
        public string LastPaymentMethod { get; set; }
        public Nullable<int> TotalNumberOfPayments { get; set; }
        public Nullable<int> CoinsAccepted { get; set; }
        public Nullable<int> CoinsRejected { get; set; }
        public string SensorTransactions { get; set; }
        public string TransactionStatus { get; set; }
        public Nullable<int> ReceiptID { get; set; }
        public string BatchID { get; set; }
        public Nullable<int> NetTimePaid { get; set; }
        public string C15_minutes_free_Used { get; set; }
        public Nullable<System.DateTime> SensorZeroTime { get; set; }
        public Nullable<int> TotalOccupiedMinute { get; set; }
        public string TimeClass1 { get; set; }
        public string TimeClass2 { get; set; }
        public string TimeClass3 { get; set; }
        public string TimeClass4 { get; set; }
        public string TimeClass5 { get; set; }
    }
}
