//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerProperty
    {
        public CustomerProperty()
        {
            this.CustomerDetails = new HashSet<CustomerDetail>();
        }
    
        public int CustomerPropertyId { get; set; }
        public int CustomerPropertyGroupId { get; set; }
        public int CustomerID { get; set; }
        public string PropertyDesc { get; set; }
        public int SortOrder { get; set; }
    
        public virtual ICollection<CustomerDetail> CustomerDetails { get; set; }
        public virtual CustomerPropertyGroup CustomerPropertyGroup { get; set; }
    }
}
