//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerBaseMeterFile
    {
        public long UniqueKey { get; set; }
        public Nullable<long> GlobalMeterID { get; set; }
        public int CustomerID { get; set; }
        public int AreaId { get; set; }
        public Nullable<int> MeterId { get; set; }
        public string FileHash { get; set; }
        public long FileSizeBytes { get; set; }
        public System.DateTime FileAdditionDate { get; set; }
        public byte[] FileRawData { get; set; }
        public string FileName { get; set; }
        public Nullable<int> Flags { get; set; }
    
        public virtual Meter Meter { get; set; }
    }
}
