//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomersAudit
    {
        public int ID { get; set; }
        public int CustomerID { get; set; }
        public string Name { get; set; }
        public string FromEmailAddress { get; set; }
        public string BankHostAddr { get; set; }
        public Nullable<int> BankHostPort { get; set; }
        public Nullable<int> BankMaxThreads { get; set; }
        public Nullable<int> BankServiceProvider { get; set; }
        public string BankStoreID { get; set; }
        public Nullable<int> ResubmitProfileID { get; set; }
        public Nullable<bool> BlackListCC { get; set; }
        public Nullable<bool> DoesCreditCashKeys { get; set; }
        public Nullable<int> UnReconcileCleanupLag { get; set; }
        public Nullable<bool> DoesBlacklistViaFD { get; set; }
        public Nullable<int> TxTiming { get; set; }
        public int UserId { get; set; }
        public System.DateTime UpdateDateTime { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> CreateDateTime { get; set; }
        public string City { get; set; }
        public Nullable<double> Latitude { get; set; }
    }
}
