//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerDetail
    {
        public int ID { get; set; }
        public int CustomerID { get; set; }
        public int CustomerPropertyId { get; set; }
        public string AdditionalValue { get; set; }
        public string ScreenName { get; set; }
        public bool IsRequired { get; set; }
        public bool IsDisplay { get; set; }
    
        public virtual CustomerProperty CustomerProperty { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
