//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerPropertyGroup
    {
        public CustomerPropertyGroup()
        {
            this.CustomerProperties = new HashSet<CustomerProperty>();
        }
    
        public int CustomerPropertyGroupId { get; set; }
        public string PropertyGroupDesc { get; set; }
        public int CustomerID { get; set; }
    
        public virtual ICollection<CustomerProperty> CustomerProperties { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
