//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiscountSchemeCustomerInfo
    {
        public int DiscountSchemeCustomerInfoId { get; set; }
        public int CustomerId { get; set; }
        public Nullable<int> DiscountSchemeId { get; set; }
        public string FromEmailAddress { get; set; }
        public string CustomerServicePhNo { get; set; }
        public Nullable<int> DiscountSchemeEmailTemplateId { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual DiscountScheme DiscountScheme { get; set; }
        public virtual DiscountSchemeEmailTemplate DiscountSchemeEmailTemplate { get; set; }
    }
}
