//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiscountSchemeStatu
    {
        public DiscountSchemeStatu()
        {
            this.DiscountUserSchemes = new HashSet<DiscountUserScheme>();
        }
    
        public int DiscountSchemeStatusId { get; set; }
        public string DiscountSchemeStatusDesc { get; set; }
    
        public virtual ICollection<DiscountUserScheme> DiscountUserSchemes { get; set; }
    }
}
