//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiscountSchemeCustomer
    {
        public int DiscountSchemeCustomerId { get; set; }
        public int DiscountSchemeId { get; set; }
        public int CustomerId { get; set; }
        public bool IsDisplay { get; set; }
        public Nullable<int> DiscountPercentage { get; set; }
        public Nullable<int> DiscountMinute { get; set; }
        public Nullable<int> MaxAmountInCent { get; set; }
        public Nullable<int> SchemeState { get; set; }
    
        public virtual AssetState AssetState { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual DiscountScheme DiscountScheme { get; set; }
    }
}
