//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiscountUserSchemeAudit
    {
        public int DiscountUserSchemeAuditId { get; set; }
        public int DiscountUserSchemeId { get; set; }
        public int UserId { get; set; }
        public int CardId { get; set; }
        public int SchemeId { get; set; }
        public Nullable<System.DateTime> ExpiryTS { get; set; }
        public System.DateTime CreatedTS { get; set; }
        public Nullable<int> ModifiedByUserId { get; set; }
        public Nullable<int> SchemeStatus { get; set; }
        public Nullable<System.DateTime> SchemeStatusDate { get; set; }
        public string StatusNote { get; set; }
        public int ChangedByUserId { get; set; }
        public System.DateTime ChangedDate { get; set; }
        public Nullable<int> CustomerId { get; set; }
    
        public virtual DiscountUserScheme DiscountUserScheme { get; set; }
    }
}
