//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiscountSchemeType
    {
        public DiscountSchemeType()
        {
            this.DiscountSchemes = new HashSet<DiscountScheme>();
        }
    
        public int DiscountSchemeTypeId { get; set; }
        public string DiscountSchemeTypeDesc { get; set; }
    
        public virtual ICollection<DiscountScheme> DiscountSchemes { get; set; }
    }
}
