//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiscountSchemeEmailTemplate
    {
        public DiscountSchemeEmailTemplate()
        {
            this.DiscountSchemeCustomerInfoes = new HashSet<DiscountSchemeCustomerInfo>();
        }
    
        public int DiscountSchemeEmailTemplateId { get; set; }
        public int EmailTemplateTypeId { get; set; }
        public string EmailText { get; set; }
        public string EmailSubject { get; set; }
        public int CustomerId { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ICollection<DiscountSchemeCustomerInfo> DiscountSchemeCustomerInfoes { get; set; }
        public virtual EmailTemplateType EmailTemplateType { get; set; }
    }
}
