//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiscountScheme
    {
        public DiscountScheme()
        {
            this.DiscountSchemeCustomers = new HashSet<DiscountSchemeCustomer>();
            this.DiscountSchemeCustomerInfoes = new HashSet<DiscountSchemeCustomerInfo>();
            this.DiscountSchemeMeters = new HashSet<DiscountSchemeMeter>();
            this.DiscountUserSchemes = new HashSet<DiscountUserScheme>();
            this.TransactionsCreditCards = new HashSet<TransactionsCreditCard>();
        }
    
        public int DiscountSchemeID { get; set; }
        public string SchemeName { get; set; }
        public Nullable<int> SchemeType { get; set; }
        public Nullable<int> DiscountPercentage { get; set; }
        public Nullable<int> DiscountMinute { get; set; }
        public Nullable<int> MaxAmountInCent { get; set; }
        public Nullable<System.DateTime> ActivationDate { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public Nullable<int> DiscountSchemeExpirationTypeId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public bool IsDisplay { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual DiscountSchemeType DiscountSchemeType { get; set; }
        public virtual DiscountSchemeExpirationType DiscountSchemeExpirationType { get; set; }
        public virtual ICollection<DiscountSchemeCustomer> DiscountSchemeCustomers { get; set; }
        public virtual ICollection<DiscountSchemeCustomerInfo> DiscountSchemeCustomerInfoes { get; set; }
        public virtual ICollection<DiscountSchemeMeter> DiscountSchemeMeters { get; set; }
        public virtual ICollection<DiscountUserScheme> DiscountUserSchemes { get; set; }
        public virtual ICollection<TransactionsCreditCard> TransactionsCreditCards { get; set; }
    }
}
