//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class EagleArea
    {
        public Nullable<long> GlobalAreaID { get; set; }
        public int CustomerID { get; set; }
        public string AreaID { get; set; }
        public string AreaName { get; set; }
        public string Description { get; set; }
    }
}
