//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventsCollectionCBRV
    {
        public int CustomerId { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public Nullable<long> EventUID { get; set; }
        public Nullable<int> AssetId { get; set; }
        public string AssetType { get; set; }
        public string AssetName { get; set; }
        public Nullable<int> AlarmCode { get; set; }
        public string EventType { get; set; }
        public Nullable<int> EventCode { get; set; }
        public Nullable<int> AreaID { get; set; }
        public Nullable<int> ZoneId { get; set; }
        public string Zone { get; set; }
        public string Area { get; set; }
        public string Street { get; set; }
        public string Suburb { get; set; }
        public string DemandArea { get; set; }
        public string TimeClass1 { get; set; }
        public string TimeClass2 { get; set; }
        public string TimeClass3 { get; set; }
        public string TimeClass4 { get; set; }
        public string TimeClass5 { get; set; }
        public Nullable<double> Meter_Reported_Amount { get; set; }
        public Nullable<double> Vendor_Reported_Amount { get; set; }
        public Nullable<float> Diff_Meter___Vendor { get; set; }
        public string CashBoxId { get; set; }
        public Nullable<System.DateTime> DateTime_of_Collection { get; set; }
        public System.DateTime DateTime_of_Insertion { get; set; }
        public string OperatorId { get; set; }
        public System.DateTime ReadTime { get; set; }
        public Nullable<long> TimeActive { get; set; }
        public int SequenceNumber { get; set; }
        public string TransactionFileName { get; set; }
        public Nullable<int> Version { get; set; }
    }
}
