//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventLogsV
    {
        public int CustomerID { get; set; }
        public int areaid { get; set; }
        public Nullable<int> AreaID2 { get; set; }
        public int MeterID { get; set; }
        public System.DateTime EventDateTime { get; set; }
        public int EventCode { get; set; }
        public int EventSource { get; set; }
        public string TechnicianKeyID { get; set; }
        public Nullable<long> GlobalMeterID { get; set; }
    }
}
