//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class FDFileTypeMeterGroup
    {
        public FDFileTypeMeterGroup()
        {
            this.AssetVersionMasters = new HashSet<AssetVersionMaster>();
        }
    
        public int FDFileTypeMeterGroupID { get; set; }
        public int FileType { get; set; }
        public Nullable<int> MeterGroup { get; set; }
        public Nullable<int> VersionGroup { get; set; }
    
        public virtual ICollection<AssetVersionMaster> AssetVersionMasters { get; set; }
        public virtual FDFileType FDFileType { get; set; }
        public virtual MeterGroup MeterGroup1 { get; set; }
        public virtual VersionGroup VersionGroup1 { get; set; }
    }
}
