//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class FDFile
    {
        public FDFile()
        {
            this.FDFilesAudits = new HashSet<FDFilesAudit>();
            this.FDHousings = new HashSet<FDHousing>();
            this.FDHousingAudits = new HashSet<FDHousingAudit>();
            this.FDJobs = new HashSet<FDJob>();
        }
    
        public long FileID { get; set; }
        public int FileType { get; set; }
        public string FileHash { get; set; }
        public string FileComments { get; set; }
        public long FileSizeBytes { get; set; }
        public System.DateTime FileAdditionDate { get; set; }
        public byte[] FileRawData { get; set; }
        public string FileName { get; set; }
        public Nullable<long> OriginalFileID { get; set; }
        public string Version { get; set; }
        public Nullable<long> AltChkSum { get; set; }
    
        public virtual FDFileType FDFileType { get; set; }
        public virtual ICollection<FDFilesAudit> FDFilesAudits { get; set; }
        public virtual ICollection<FDHousing> FDHousings { get; set; }
        public virtual ICollection<FDHousingAudit> FDHousingAudits { get; set; }
        public virtual ICollection<FDJob> FDJobs { get; set; }
    }
}
