//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class FDHousingAudit
    {
        public int HousingId { get; set; }
        public long FileID { get; set; }
        public int FileType { get; set; }
        public System.DateTime UpdateTS { get; set; }
    
        public virtual FDFileType FDFileType { get; set; }
        public virtual HousingMaster HousingMaster { get; set; }
        public virtual FDFile FDFile { get; set; }
    }
}
