//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class FDJobStatu
    {
        public FDJobStatu()
        {
            this.FDJobHistories = new HashSet<FDJobHistory>();
            this.FDJobs = new HashSet<FDJob>();
        }
    
        public int JobStatus { get; set; }
        public string StatusDesc { get; set; }
    
        public virtual ICollection<FDJobHistory> FDJobHistories { get; set; }
        public virtual ICollection<FDJob> FDJobs { get; set; }
    }
}
