//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gateway
    {
        public Gateway()
        {
            this.SensorMappings = new HashSet<SensorMapping>();
            this.SensorPaymentTransactions = new HashSet<SensorPaymentTransaction>();
            this.Transactions = new HashSet<Transaction>();
            this.VersionProfileMeters = new HashSet<VersionProfileMeter>();
            this.MeterMaps = new HashSet<MeterMap>();
            this.SensorPaymentTransactionCurrents = new HashSet<SensorPaymentTransactionCurrent>();
        }
    
        public int GateWayID { get; set; }
        public int CustomerID { get; set; }
        public string Description { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public string Location { get; set; }
        public Nullable<int> GatewayState { get; set; }
        public Nullable<int> GatewayType { get; set; }
        public Nullable<System.DateTime> InstallDateTime { get; set; }
        public Nullable<int> TimeZoneID { get; set; }
        public Nullable<int> DemandZone { get; set; }
        public string CAMID { get; set; }
        public string CELID { get; set; }
        public Nullable<int> PowerSource { get; set; }
        public string HWVersion { get; set; }
        public string Manufacturer { get; set; }
        public Nullable<int> GatewayModel { get; set; }
        public Nullable<System.DateTime> OperationalStatusTime { get; set; }
        public Nullable<System.DateTime> LastPreventativeMaintenance { get; set; }
        public Nullable<System.DateTime> NextPreventativeMaintenance { get; set; }
        public Nullable<System.DateTime> WarrantyExpiration { get; set; }
        public Nullable<int> OperationalStatus { get; set; }
        public Nullable<System.DateTime> OperationalStatusEndTime { get; set; }
        public string OperationalStatusComment { get; set; }
    
        public virtual AssetState AssetState { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual TimeZone TimeZone { get; set; }
        public virtual MechanismMaster MechanismMaster { get; set; }
        public virtual OperationalStatu OperationalStatu { get; set; }
        public virtual ICollection<SensorMapping> SensorMappings { get; set; }
        public virtual ICollection<SensorPaymentTransaction> SensorPaymentTransactions { get; set; }
        public virtual ICollection<Transaction> Transactions { get; set; }
        public virtual ICollection<VersionProfileMeter> VersionProfileMeters { get; set; }
        public virtual ICollection<MeterMap> MeterMaps { get; set; }
        public virtual ICollection<SensorPaymentTransactionCurrent> SensorPaymentTransactionCurrents { get; set; }
    }
}
