//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class HolidayRateForConfiguration
    {
        public long HolidayRatesId { get; set; }
        public long HolidayRateConfigurationId { get; set; }
        public long HolidayRateId { get; set; }
    
        public virtual HolidayRate HolidayRate { get; set; }
        public virtual HolidayRateConfiguration HolidayRateConfiguration { get; set; }
    }
}
