//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class HousingType
    {
        public HousingType()
        {
            this.HousingMasters = new HashSet<HousingMaster>();
        }
    
        public int HousingTypeID { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<HousingMaster> HousingMasters { get; set; }
    }
}
