//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class HousingMaster
    {
        public HousingMaster()
        {
            this.FDHousings = new HashSet<FDHousing>();
            this.FDHousingAudits = new HashSet<FDHousingAudit>();
            this.MeterMapAudits = new HashSet<MeterMapAudit>();
            this.MeterMaps = new HashSet<MeterMap>();
        }
    
        public int HousingId { get; set; }
        public string HousingName { get; set; }
        public int Customerid { get; set; }
        public string Block { get; set; }
        public string StreetName { get; set; }
        public string StreetType { get; set; }
        public string StreetDirection { get; set; }
        public string StreetNotes { get; set; }
        public Nullable<int> HousingTypeID { get; set; }
        public string DoorLockId { get; set; }
        public string MechLockId { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> InactiveRemarkID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string Notes { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ICollection<FDHousing> FDHousings { get; set; }
        public virtual ICollection<FDHousingAudit> FDHousingAudits { get; set; }
        public virtual HousingType HousingType { get; set; }
        public virtual InactiveRemark InactiveRemark { get; set; }
        public virtual ICollection<MeterMapAudit> MeterMapAudits { get; set; }
        public virtual ICollection<MeterMap> MeterMaps { get; set; }
    }
}
