//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportDirectory
    {
        public string IncomingDir { get; set; }
        public string OutgoingDir { get; set; }
        public int CustomerID { get; set; }
        public Nullable<int> PollTime { get; set; }
    }
}
