//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaintenanceEventsV
    {
        public int CustomerID { get; set; }
        public Nullable<long> EventUID { get; set; }
        public int AssetId { get; set; }
        public string AssetType { get; set; }
        public string AssetName { get; set; }
        public Nullable<int> AlarmCode { get; set; }
        public string EventClass { get; set; }
        public int EventCode { get; set; }
        public Nullable<int> AreaId2 { get; set; }
        public Nullable<int> ZoneId { get; set; }
        public string Street { get; set; }
        public string Suburb { get; set; }
        public string DemandArea { get; set; }
        public string TimeClass1 { get; set; }
        public string TimeClass2 { get; set; }
        public string TimeClass3 { get; set; }
        public string TimeClass4 { get; set; }
        public string TimeClass5 { get; set; }
        public string AlarmDescription { get; set; }
        public string AlarmClass { get; set; }
        public Nullable<int> Repair_Code { get; set; }
        public string Source { get; set; }
        public string Technician_Name { get; set; }
        public Nullable<int> TechnicianID { get; set; }
        public Nullable<int> WorkOrderId { get; set; }
        public System.DateTime DateTime { get; set; }
        public System.DateTime TimeOfNotification { get; set; }
        public Nullable<System.DateTime> TimeOfClearance { get; set; }
        public Nullable<System.DateTime> TimeDueSLA { get; set; }
        public string IsClosed { get; set; }
        public string Zone { get; set; }
        public string Area { get; set; }
    }
}
