//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeterDiagnostic
    {
        public int ID { get; set; }
        public int CustomerID { get; set; }
        public int AreaId { get; set; }
        public int MeterId { get; set; }
        public System.DateTime DiagTime { get; set; }
        public System.DateTime ReceivedTime { get; set; }
        public int DiagnosticType { get; set; }
        public string DiagnosticValue { get; set; }
        public Nullable<long> EventUID { get; set; }
        public Nullable<int> TimeType1 { get; set; }
        public Nullable<int> TimeType2 { get; set; }
        public Nullable<int> TimeType3 { get; set; }
        public Nullable<int> TimeType4 { get; set; }
        public Nullable<int> TimeType5 { get; set; }
    
        public virtual MeterDiagnosticType MeterDiagnosticType { get; set; }
    }
}
