//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class metermap_bk
    {
        public int Customerid { get; set; }
        public int Areaid { get; set; }
        public int MeterId { get; set; }
        public Nullable<int> ZoneId { get; set; }
        public int HousingId { get; set; }
        public Nullable<int> MechId { get; set; }
        public Nullable<int> AreaId2 { get; set; }
        public Nullable<int> CollRouteId { get; set; }
        public Nullable<int> EnfRouteId { get; set; }
        public Nullable<int> MaintRouteId { get; set; }
        public int id { get; set; }
        public Nullable<int> CustomGroup1 { get; set; }
        public Nullable<int> CustomGroup2 { get; set; }
        public Nullable<int> CustomGroup3 { get; set; }
        public Nullable<int> SubAreaID { get; set; }
        public Nullable<int> GatewayID { get; set; }
        public Nullable<int> SensorID { get; set; }
        public Nullable<int> CashBoxID { get; set; }
    }
}
