//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeterDiagnosticTypeCustomer
    {
        public int CustomerId { get; set; }
        public int DiagnosticType { get; set; }
        public Nullable<bool> IsDisplay { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual MeterDiagnosticType MeterDiagnosticType { get; set; }
    }
}
