//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeterMapName
    {
        public int customerid { get; set; }
        public int areaid { get; set; }
        public int meterid { get; set; }
        public string areaname { get; set; }
        public string zone { get; set; }
        public string locationid { get; set; }
        public Nullable<int> housingid { get; set; }
        public string collroute { get; set; }
        public string MaintRoute { get; set; }
        public string EnforceRoute { get; set; }
        public string CustomGroup1 { get; set; }
        public string CustomGroup2 { get; set; }
        public string CustomGroup3 { get; set; }
    }
}
