//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeterZoneMap
    {
        public int Id { get; set; }
        public int customerid { get; set; }
        public int areaid { get; set; }
        public int meterid { get; set; }
        public int ZoneId { get; set; }
    
        public virtual Meter Meter { get; set; }
        public virtual Zone Zone { get; set; }
    }
}
