//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeterMapping
    {
        public int MeterMappingId { get; set; }
        public int SpaceId { get; set; }
        public int DuncanCustomerId { get; set; }
        public int DuncanAreaId { get; set; }
        public int DuncanMeterId { get; set; }
        public int DuncanBayId { get; set; }
        public string Remark { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public Nullable<int> VendorId { get; set; }
    }
}
