//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeterUptimeV
    {
        public int CustomerID { get; set; }
        public System.DateTime ReportingDate { get; set; }
        public string MeterName { get; set; }
        public int MeterID { get; set; }
        public string MeterType { get; set; }
        public Nullable<int> AreaId2 { get; set; }
        public Nullable<int> ZoneId { get; set; }
        public string Area { get; set; }
        public string Zone { get; set; }
        public string Street { get; set; }
        public string Suburb { get; set; }
        public Nullable<int> TotalRegulatedMinutes { get; set; }
        public Nullable<int> TotalRegulatedDowntimeMinutes { get; set; }
        public Nullable<int> RegulatedUpTimePCT { get; set; }
        public string CoinCollected { get; set; }
        public Nullable<int> CoinRejects { get; set; }
        public Nullable<int> CCTransactions { get; set; }
        public Nullable<int> CCReadErrors { get; set; }
        public string SpaceDemandType { get; set; }
    }
}
