//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class MTX_MECHINFO
    {
        public Nullable<int> AUTOPROC_UNIQUEKEY { get; set; }
        public Nullable<System.DateTime> CUSTOM1EXPORTDATE { get; set; }
        public Nullable<System.DateTime> CUSTOM2EXPORTDATE { get; set; }
        public Nullable<System.DateTime> CUSTOM3EXPORTDATE { get; set; }
        public Nullable<int> ENCRYPTIONKEYID { get; set; }
        public string FORMNAME { get; set; }
        public Nullable<int> FORMREV { get; set; }
        public Nullable<System.DateTime> LASTAUDITDATE { get; set; }
        public Nullable<System.DateTime> LASTCOLLECTIONDATE { get; set; }
        public Nullable<System.DateTime> LASTINVENTORYDATE { get; set; }
        public Nullable<System.DateTime> LASTOPCHECKDATE { get; set; }
        public Nullable<System.DateTime> LASTOUTAGEDATE { get; set; }
        public Nullable<System.DateTime> LASTPROGRAMDATE { get; set; }
        public Nullable<System.DateTime> LASTREPAIRDATE { get; set; }
        public string MECHSERIALNUMBER { get; set; }
        public string MECHTYPEID { get; set; }
        public string OPERABLE { get; set; }
        public string PCB_ASSEMBLYREV { get; set; }
        public string PCB_BOARDNUMBER { get; set; }
        public string PCB_MANUFACTUREWEEK { get; set; }
        public string PCB_MANUFACTUREYEAR { get; set; }
        public string PCB_PAPERCLIPVAL { get; set; }
        public string PCB_SOFTWAREREV { get; set; }
        public string PCB_VENDORID { get; set; }
        public Nullable<int> POLELOCATION_FK { get; set; }
        public string RATEPROGRAMID { get; set; }
        public Nullable<System.DateTime> RECCREATIONDATE { get; set; }
        public string RECOVEREDBYHH { get; set; }
        public Nullable<double> REGREADCASH { get; set; }
        public Nullable<double> REGREADDEBIT { get; set; }
        public Nullable<int> REINOROWVERSION { get; set; }
        public Nullable<System.DateTime> STANDARDEXPORTDATE { get; set; }
        public Nullable<int> SUBCONFIGKEY { get; set; }
        public Nullable<int> TABLEREV { get; set; }
        public Nullable<int> TBLENCRYPTVERSION { get; set; }
        public Nullable<int> TRANSACTIONKEY { get; set; }
        public string TRANSACTIONNAME { get; set; }
        public int UNIQUEKEY { get; set; }
        public Nullable<System.DateTime> USERDEF1EXPORTDATE { get; set; }
        public Nullable<System.DateTime> USERDEF2EXPORTDATE { get; set; }
        public Nullable<System.DateTime> USERDEF3EXPORTDATE { get; set; }
        public Nullable<System.DateTime> USERDEF4EXPORTDATE { get; set; }
        public Nullable<System.DateTime> USERDEF5EXPORTDATE { get; set; }
        public Nullable<System.DateTime> WIRELESSEXPORTDATE_AUTOPROC { get; set; }
    }
}
