//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class NoCommunicationV
    {
        public int CustomerId { get; set; }
        public int Areaid { get; set; }
        public int AssetId { get; set; }
        public Nullable<long> GlobalMeterId { get; set; }
        public string AssetName { get; set; }
        public string Suburb { get; set; }
        public string Street { get; set; }
        public string Area { get; set; }
        public string Zone { get; set; }
    }
}
