//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class OccupancyV
    {
        public int Customerid { get; set; }
        public long SpaceId { get; set; }
        public Nullable<int> SensorID { get; set; }
        public int MeterId { get; set; }
        public string OccupancyStatus { get; set; }
        public string OperationalStatus { get; set; }
        public string Street { get; set; }
        public string SpaceType { get; set; }
        public string NonCompliantStatus { get; set; }
        public string TimeClass1 { get; set; }
        public string TimeClass2 { get; set; }
        public string TimeClass3 { get; set; }
        public string TimeClass4 { get; set; }
        public string TimeClass5 { get; set; }
        public string Suburb { get; set; }
        public string Area { get; set; }
        public string Zone { get; set; }
        public string AssetName { get; set; }
        public Nullable<int> AssetId { get; set; }
        public string AssetType { get; set; }
        public System.DateTime ArrivalTime { get; set; }
        public long SensorPaymentTransactionID { get; set; }
        public Nullable<System.DateTime> DepartureTime { get; set; }
        public Nullable<int> TotalOccupiedMinute { get; set; }
        public Nullable<int> TotalTimePaidMinute { get; set; }
        public Nullable<int> TotalAmountInCent { get; set; }
        public string BayName { get; set; }
        public int BayNumber { get; set; }
        public string DemandArea { get; set; }
    }
}
