//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class OccupancyRateSummaryV
    {
        public System.DateTime ArrivalTime { get; set; }
        public Nullable<System.DateTime> DepartureTime { get; set; }
        public Nullable<int> Customerid { get; set; }
        public long SensorPaymentTransactionID { get; set; }
        public long SpaceId { get; set; }
        public string SpaceType { get; set; }
        public Nullable<int> AreaID { get; set; }
        public Nullable<int> ZoneId { get; set; }
        public string OccupancyStatus { get; set; }
        public string OperationalStatus { get; set; }
        public string Street { get; set; }
        public string Area { get; set; }
        public string Zone { get; set; }
        public string Suburb { get; set; }
        public string NonCompliantStatus { get; set; }
        public Nullable<System.DateTime> LastTxExpiryTime { get; set; }
        public Nullable<int> OverstayMinutes { get; set; }
        public string TimeClass1 { get; set; }
        public string TimeClass2 { get; set; }
        public string TimeClass3 { get; set; }
        public string TimeClass4 { get; set; }
        public string TimeClass5 { get; set; }
        public Nullable<int> SensorID { get; set; }
        public string SensorName { get; set; }
        public Nullable<int> MeterId { get; set; }
        public string MeterName { get; set; }
        public string MeterType { get; set; }
        public Nullable<int> TotalOccupiedMinute { get; set; }
        public Nullable<int> TotalTimePaidMinute { get; set; }
        public string FreeParkingUsed { get; set; }
        public Nullable<int> FreeParkingTime { get; set; }
        public Nullable<int> FreeParkingMinute { get; set; }
        public string DemandArea { get; set; }
    }
}
