//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class OccupancyStatu
    {
        public OccupancyStatu()
        {
            this.ParkingSpaceOccupancies = new HashSet<ParkingSpaceOccupancy>();
            this.SensorPaymentTransactions = new HashSet<SensorPaymentTransaction>();
            this.SensorPaymentTransactionCurrents = new HashSet<SensorPaymentTransactionCurrent>();
        }
    
        public int StatusID { get; set; }
        public string StatusDesc { get; set; }
    
        public virtual ICollection<ParkingSpaceOccupancy> ParkingSpaceOccupancies { get; set; }
        public virtual ICollection<SensorPaymentTransaction> SensorPaymentTransactions { get; set; }
        public virtual ICollection<SensorPaymentTransactionCurrent> SensorPaymentTransactionCurrents { get; set; }
    }
}
