//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class OLTCardHash
    {
        public int Id { get; set; }
        public System.DateTime InsDate { get; set; }
        public int Fdigit { get; set; }
        public int Ldigit { get; set; }
        public int CustomerId { get; set; }
    }
}
