//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class OperationMode
    {
        public OperationMode()
        {
            this.RateSchedules = new HashSet<RateSchedule>();
        }
    
        public int OperationModeId { get; set; }
        public string OperationModeDesc { get; set; }
    
        public virtual ICollection<RateSchedule> RateSchedules { get; set; }
    }
}
