//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class OperationalStatu
    {
        public OperationalStatu()
        {
            this.CashBoxes = new HashSet<CashBox>();
            this.Gateways = new HashSet<Gateway>();
            this.Meters = new HashSet<Meter>();
            this.ParkingSpaces = new HashSet<ParkingSpace>();
            this.SensorPaymentTransactions = new HashSet<SensorPaymentTransaction>();
            this.Sensors = new HashSet<Sensor>();
            this.SensorPaymentTransactionCurrents = new HashSet<SensorPaymentTransactionCurrent>();
        }
    
        public int OperationalStatusId { get; set; }
        public string OperationalStatusDesc { get; set; }
    
        public virtual ICollection<CashBox> CashBoxes { get; set; }
        public virtual ICollection<Gateway> Gateways { get; set; }
        public virtual ICollection<Meter> Meters { get; set; }
        public virtual ICollection<ParkingSpace> ParkingSpaces { get; set; }
        public virtual ICollection<SensorPaymentTransaction> SensorPaymentTransactions { get; set; }
        public virtual ICollection<Sensor> Sensors { get; set; }
        public virtual ICollection<SensorPaymentTransactionCurrent> SensorPaymentTransactionCurrents { get; set; }
    }
}
