//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAMCustomerMap
    {
        public int CustomerId { get; set; }
        public string CustomerCode { get; set; }
        public int ClusterId { get; set; }
        public int BayNum { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
