//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAMTx
    {
        public int SequenceId { get; set; }
        public int CustomerId { get; set; }
        public int MeterId { get; set; }
        public int Bay { get; set; }
        public System.DateTime Expiry { get; set; }
        public int Duration { get; set; }
        public bool TopUp { get; set; }
        public int TransactionType { get; set; }
        public int AmountCent { get; set; }
        public System.DateTime Received { get; set; }
        public Nullable<System.DateTime> LastProcessed { get; set; }
        public Nullable<int> LastResult { get; set; }
        public int Attempt { get; set; }
        public Nullable<System.DateTime> TRANSDATETIME { get; set; }
        public Nullable<System.DateTime> MaxReachedAt { get; set; }
        public Nullable<int> TIMECREDIT { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
