//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParkVehicle
    {
        public ParkVehicle()
        {
            this.ParkSpaceRights = new HashSet<ParkSpaceRight>();
        }
    
        public int VehicleID { get; set; }
        public string LPNumber { get; set; }
        public string LPLocation { get; set; }
        public string VMake { get; set; }
        public string VModel { get; set; }
        public string VColour { get; set; }
    
        public virtual ICollection<ParkSpaceRight> ParkSpaceRights { get; set; }
    }
}
