//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParkingSpaceMeterBayMap
    {
        public int ParkingSpaceMeterBayMapId { get; set; }
        public long SensorParkingSpaceID { get; set; }
        public int CustomerId { get; set; }
        public int AreaId { get; set; }
        public int MeterId { get; set; }
        public int BayNumber { get; set; }
    
        public virtual ParkingSpace ParkingSpace { get; set; }
    }
}
