//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParkingOccupancyReport
    {
        public int id { get; set; }
        public string ParkingSpaceOccupancyId { get; set; }
        public Nullable<int> LastStatus { get; set; }
        public Nullable<System.DateTime> LastUpdatedTS { get; set; }
        public Nullable<int> GCustomerid { get; set; }
        public Nullable<int> Time { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.DateTime> ExpiryTime { get; set; }
        public Nullable<int> Enforceable { get; set; }
    }
}
