//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParkingSpacesAudit
    {
        public long ParkingSpacesAuditId { get; set; }
        public int UserId { get; set; }
        public System.DateTime UpdateDateTime { get; set; }
        public long ParkingSpaceId { get; set; }
        public int ServerID { get; set; }
        public int CustomerID { get; set; }
        public int AreaId { get; set; }
        public int MeterId { get; set; }
        public int BayNumber { get; set; }
        public System.DateTime AddedDateTime { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<bool> HasSensor { get; set; }
        public Nullable<int> SpaceStatus { get; set; }
        public Nullable<System.DateTime> DateActivated { get; set; }
        public string Comments { get; set; }
        public string DisplaySpaceNum { get; set; }
        public Nullable<int> DemandZoneId { get; set; }
        public Nullable<System.DateTime> InstallDate { get; set; }
        public Nullable<int> ParkingSpaceType { get; set; }
        public Nullable<int> OperationalStatus { get; set; }
        public Nullable<System.DateTime> OperationalStatusTime { get; set; }
        public Nullable<int> AssetPendingReasonId { get; set; }
    
        public virtual AssetPendingReason AssetPendingReason { get; set; }
    }
}
