//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParkSpaceRight
    {
        public int VehicleId { get; set; }
        public int customerid { get; set; }
        public int ZoneId { get; set; }
        public Nullable<int> SpaceNum { get; set; }
        public int txseqNum { get; set; }
        public int ReceiptId { get; set; }
        public int amount { get; set; }
        public System.DateTime transactionTime { get; set; }
        public System.DateTime currentdatetime { get; set; }
        public System.DateTime StartDateTime { get; set; }
        public System.DateTime AutoDeactivateDateTime { get; set; }
        public string ProductDescription { get; set; }
    
        public virtual ParkVehicle ParkVehicle { get; set; }
    }
}
