//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParkingSpaceOccupancyAudit
    {
        public ParkingSpaceOccupancyAudit()
        {
            this.SensorPaymentTransactions = new HashSet<SensorPaymentTransaction>();
            this.SensorPaymentTransactions1 = new HashSet<SensorPaymentTransaction>();
            this.SensorPaymentTransactionCurrents = new HashSet<SensorPaymentTransactionCurrent>();
            this.SensorPaymentTransactionCurrents1 = new HashSet<SensorPaymentTransactionCurrent>();
        }
    
        public long AuditID { get; set; }
        public long ParkingSpaceOccupancyId { get; set; }
        public int LastStatus { get; set; }
        public System.DateTime LastUpdatedTS { get; set; }
        public Nullable<System.DateTime> RecCreationDate { get; set; }
        public string ResultStatus { get; set; }
        public Nullable<int> GCustomerid { get; set; }
        public Nullable<int> GAreaId { get; set; }
        public Nullable<int> GMeterId { get; set; }
        public byte[] DiagnosticData { get; set; }
        public Nullable<int> Regulated { get; set; }
        public Nullable<int> TimeType1 { get; set; }
        public Nullable<int> TimeType2 { get; set; }
        public Nullable<int> TimeType3 { get; set; }
        public Nullable<int> TimeType4 { get; set; }
        public Nullable<int> TimeType5 { get; set; }
        public Nullable<System.DateTime> EndTS { get; set; }
        public Nullable<int> DurationSeconds { get; set; }
        public string hexacode { get; set; }
    
        public virtual ParkingSpaceOccupancy ParkingSpaceOccupancy { get; set; }
        public virtual ICollection<SensorPaymentTransaction> SensorPaymentTransactions { get; set; }
        public virtual ICollection<SensorPaymentTransaction> SensorPaymentTransactions1 { get; set; }
        public virtual ICollection<SensorPaymentTransactionCurrent> SensorPaymentTransactionCurrents { get; set; }
        public virtual ICollection<SensorPaymentTransactionCurrent> SensorPaymentTransactionCurrents1 { get; set; }
    }
}
