//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParkingSpaceDetail
    {
        public long ID { get; set; }
        public long ParkingSpaceId { get; set; }
        public int SpaceType { get; set; }
        public int HBInterval { get; set; }
        public string ExpiryLevel { get; set; }
        public string PercentLevel { get; set; }
    
        public virtual ParkingSpace ParkingSpace { get; set; }
        public virtual SpaceType SpaceType1 { get; set; }
    }
}
