//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Part
    {
        public Part()
        {
            this.WorkOrderParts = new HashSet<WorkOrderPart>();
        }
    
        public long PartId { get; set; }
        public string PartName { get; set; }
        public Nullable<int> MeterGroup { get; set; }
        public Nullable<int> Category { get; set; }
        public string PartDesc { get; set; }
        public Nullable<int> CostInCent { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> Mechanism { get; set; }
    
        public virtual MechanismMaster MechanismMaster { get; set; }
        public virtual MeterGroup MeterGroup1 { get; set; }
        public virtual ICollection<WorkOrderPart> WorkOrderParts { get; set; }
    }
}
