//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class PPOStatusCode
    {
        public PPOStatusCode()
        {
            this.PPOImports = new HashSet<PPOImport>();
        }
    
        public int PPOStatusCode1 { get; set; }
        public string PPOStatusDesc { get; set; }
        public string PPOStatusType { get; set; }
        public string PPOStatusShortDesc { get; set; }
    
        public virtual ICollection<PPOImport> PPOImports { get; set; }
    }
}
