//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Process
    {
        public Process()
        {
            this.ScheduleProcesses = new HashSet<ScheduleProcess>();
        }
    
        public string ProcessID { get; set; }
        public string ProcessType { get; set; }
        public string ProcessDescription { get; set; }
    
        public virtual ProcessType ProcessType1 { get; set; }
        public virtual ICollection<ScheduleProcess> ScheduleProcesses { get; set; }
    }
}
