//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropertyGroup
    {
        public PropertyGroup()
        {
            this.LookupItems = new HashSet<LookupItem>();
        }
    
        public int PropertyGroupId { get; set; }
        public string PropertyGroupDesc { get; set; }
    
        public virtual ICollection<LookupItem> LookupItems { get; set; }
    }
}
