//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class PushStatu
    {
        public int ID { get; set; }
        public int Customerid { get; set; }
        public int AreaId { get; set; }
        public int MeterId { get; set; }
        public int Bay { get; set; }
        public System.DateTime Expt { get; set; }
        public System.DateTime Pushed { get; set; }
        public Nullable<System.DateTime> Acknowledged { get; set; }
        public Nullable<int> Attempt { get; set; }
    
        public virtual Meter Meter { get; set; }
    }
}
