//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class pv_CustomerSensorTransactions
    {
        public long TransactionId { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string AssetName { get; set; }
        public Nullable<int> AssetId { get; set; }
        public string AssetType { get; set; }
        public Nullable<int> AreaId { get; set; }
        public string Area { get; set; }
        public Nullable<int> BayId { get; set; }
        public Nullable<int> ZoneId { get; set; }
        public string Zone { get; set; }
        public string DemandArea { get; set; }
        public string Suburb { get; set; }
        public Nullable<int> GatewayId { get; set; }
        public Nullable<long> SpaceId { get; set; }
        public string Street { get; set; }
        public Nullable<int> DiscountSchemaId { get; set; }
        public Nullable<int> AmountPaid { get; set; }
        public string SpaceStatus { get; set; }
        public string TransactionType { get; set; }
        public string PaymentStatusType { get; set; }
        public Nullable<int> TimeType1 { get; set; }
        public Nullable<int> TimeType2 { get; set; }
        public Nullable<int> TimeType3 { get; set; }
        public Nullable<int> TimeType4 { get; set; }
        public Nullable<int> TimeType5 { get; set; }
        public string CardNumHash { get; set; }
        public Nullable<long> SensorPaymentTransactionId { get; set; }
        public Nullable<bool> IsSensorTransaction { get; set; }
        public string CcLast4 { get; set; }
        public Nullable<int> TimePaid { get; set; }
        public Nullable<int> CardType { get; set; }
        public string SettleBatchID { get; set; }
        public Nullable<System.DateTime> BatchDate { get; set; }
    }
}
