//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class pv_EventsCollectionCommEvent
    {
        public int CustomerId { get; set; }
        public System.DateTime DateTime { get; set; }
        public Nullable<long> EventUID { get; set; }
        public int AssetId { get; set; }
        public string AssetType { get; set; }
        public string AssetName { get; set; }
        public Nullable<int> AlarmCode { get; set; }
        public string EventClass { get; set; }
        public int EventCode { get; set; }
        public Nullable<int> AreaID { get; set; }
        public Nullable<int> ZoneId { get; set; }
        public string Street { get; set; }
        public string Suburb { get; set; }
        public string DemandArea { get; set; }
        public Nullable<int> TimeType1 { get; set; }
        public Nullable<int> TimeType2 { get; set; }
        public Nullable<int> TimeType3 { get; set; }
        public Nullable<int> TimeType4 { get; set; }
        public Nullable<int> TimeType5 { get; set; }
        public double Amount { get; set; }
        public System.DateTime CollectionTime { get; set; }
        public Nullable<System.DateTime> InsertionTime { get; set; }
        public string PreviousCBID { get; set; }
        public string NewCBID { get; set; }
        public Nullable<int> SequenceNumber { get; set; }
        public string Zone { get; set; }
        public string Area { get; set; }
    }
}
