//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class qCBImpFile
    {
        public Nullable<System.DateTime> DateTimeImp { get; set; }
        public Nullable<int> xFileProcessID { get; set; }
        public int CustomerId { get; set; }
        public string FileNameImp { get; set; }
    }
}
