//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class RateScheduleForConfiguration
    {
        public long RateSchedulesId { get; set; }
        public long RateScheduleConfigurationId { get; set; }
        public long RateScheduleId { get; set; }
    
        public virtual RateSchedule RateSchedule { get; set; }
        public virtual RateScheduleConfiguration RateScheduleConfiguration { get; set; }
    }
}
