//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class RateTransmissionJob
    {
        public long ID { get; set; }
        public long TransmissionDetailsID { get; set; }
        public Nullable<long> JobID { get; set; }
        public Nullable<System.DateTime> PushQueuedTS { get; set; }
        public Nullable<System.DateTime> ActivatedTS { get; set; }
        public Nullable<System.DateTime> AckTS { get; set; }
        public Nullable<System.DateTime> Emailed { get; set; }
        public int MeterId { get; set; }
        public Nullable<long> TransmissionID { get; set; }
    
        public virtual FDJob FDJob { get; set; }
        public virtual RateTransmissionDetail RateTransmissionDetail { get; set; }
    }
}
