//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class RateSchedule
    {
        public RateSchedule()
        {
            this.RateScheduleForConfigurations = new HashSet<RateScheduleForConfiguration>();
        }
    
        public long RateScheduleId { get; set; }
        public int CustomerId { get; set; }
        public int ScheduleNumber { get; set; }
        public int DayOfWeek { get; set; }
        public int StartTimeHour { get; set; }
        public int StartTimeMinute { get; set; }
        public int OperationMode { get; set; }
        public Nullable<int> MessageSequence { get; set; }
        public Nullable<bool> LockMaxTime { get; set; }
        public Nullable<long> TariffRateId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public bool IsActive { get; set; }
        public Nullable<long> TariffRateConfigurationID { get; set; }
    
        public virtual DayOfWeek DayOfWeek1 { get; set; }
        public virtual OperationMode OperationMode1 { get; set; }
        public virtual ICollection<RateScheduleForConfiguration> RateScheduleForConfigurations { get; set; }
    }
}
