//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class RateTransmission
    {
        public RateTransmission()
        {
            this.RateTransmissionDetails = new HashSet<RateTransmissionDetail>();
        }
    
        public long TransmissionID { get; set; }
        public System.DateTime ImplementationDate { get; set; }
        public System.DateTime ReceivedTS { get; set; }
        public Nullable<int> ChangeType { get; set; }
        public Nullable<System.DateTime> Emailed { get; set; }
        public Nullable<System.DateTime> SuccessTs { get; set; }
        public Nullable<System.DateTime> SlaAckTs { get; set; }
        public int CustomerId { get; set; }
    
        public virtual ICollection<RateTransmissionDetail> RateTransmissionDetails { get; set; }
    }
}
