//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class RejectedDiscount
    {
        public int ID_ { get; set; }
        public Nullable<short> CustomerId { get; set; }
        public Nullable<byte> AreaId { get; set; }
        public Nullable<int> MeterId { get; set; }
        public Nullable<System.DateTime> TransDateTime { get; set; }
        public Nullable<int> ReceiptNo { get; set; }
        public Nullable<int> AmountInCents { get; set; }
        public Nullable<int> BayNumber { get; set; }
        public string CardNumHash { get; set; }
    }
}
