//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public Schedule()
        {
            this.ScheduledMeters = new HashSet<ScheduledMeter>();
            this.ScheduleProcesses = new HashSet<ScheduleProcess>();
        }
    
        public int CustomerID { get; set; }
        public int ScheduleID { get; set; }
        public System.DateTime StartTime { get; set; }
        public int PeriodSec { get; set; }
        public string Description { get; set; }
        public string Mon { get; set; }
        public string Tue { get; set; }
        public string Wed { get; set; }
        public string Thu { get; set; }
        public string Fri { get; set; }
        public string Sat { get; set; }
        public string Sun { get; set; }
        public int DayOfMonth { get; set; }
        public int MonthNo { get; set; }
        public string ProcessType { get; set; }
        public Nullable<int> BankID { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ICollection<ScheduledMeter> ScheduledMeters { get; set; }
        public virtual ICollection<ScheduleProcess> ScheduleProcesses { get; set; }
    }
}
