//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduledMeter
    {
        public Nullable<long> GlobalMeterId { get; set; }
        public int CustomerID { get; set; }
        public int ScheduleID { get; set; }
        public int AreaID { get; set; }
        public int MeterId { get; set; }
        public int OrderNo { get; set; }
    
        public virtual Meter Meter { get; set; }
        public virtual Schedule Schedule { get; set; }
    }
}
