//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduleProcess
    {
        public int CustomerID { get; set; }
        public int ScheduleID { get; set; }
        public int ProcessOrder { get; set; }
        public string ProcessID { get; set; }
    
        public virtual Process Process { get; set; }
        public virtual Schedule Schedule { get; set; }
    }
}
