//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class SensorMappingAudit
    {
        public int SensorMappingAuditID { get; set; }
        public int SensorMappingID { get; set; }
        public int CustomerID { get; set; }
        public int SensorID { get; set; }
        public Nullable<long> ParkingSpaceID { get; set; }
        public int GatewayID { get; set; }
        public bool IsPrimaryGateway { get; set; }
        public System.DateTime ChangeDate { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> AssetPendingReasonId { get; set; }
    
        public virtual AssetPendingReason AssetPendingReason { get; set; }
        public virtual SensorMapping SensorMapping { get; set; }
    }
}
