//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sensor
    {
        public Sensor()
        {
            this.SensorMappings = new HashSet<SensorMapping>();
            this.SensorPaymentTransactions = new HashSet<SensorPaymentTransaction>();
            this.VersionProfileMeters = new HashSet<VersionProfileMeter>();
            this.MeterMaps = new HashSet<MeterMap>();
            this.SensorPaymentTransactionCurrents = new HashSet<SensorPaymentTransactionCurrent>();
        }
    
        public int CustomerID { get; set; }
        public int SensorID { get; set; }
        public byte[] BarCodeText { get; set; }
        public string Description { get; set; }
        public string GSMNumber { get; set; }
        public Nullable<long> GlobalMeterID { get; set; }
        public double Latitude { get; set; }
        public double Longitude { get; set; }
        public string Location { get; set; }
        public string SensorName { get; set; }
        public int SensorState { get; set; }
        public Nullable<int> SensorType { get; set; }
        public System.DateTime InstallDateTime { get; set; }
        public Nullable<int> DemandZone { get; set; }
        public string Comments { get; set; }
        public Nullable<int> RoadWayType { get; set; }
        public Nullable<long> ParkingSpaceId { get; set; }
        public Nullable<int> SensorModel { get; set; }
        public Nullable<int> OperationalStatus { get; set; }
        public Nullable<System.DateTime> WarrantyExpiration { get; set; }
        public Nullable<System.DateTime> OperationalStatusTime { get; set; }
        public Nullable<System.DateTime> LastPreventativeMaintenance { get; set; }
        public Nullable<System.DateTime> NextPreventativeMaintenance { get; set; }
        public Nullable<System.DateTime> OperationalStatusEndTime { get; set; }
        public string OperationalStatusComment { get; set; }
    
        public virtual AssetState AssetState { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual MechanismMaster MechanismMaster { get; set; }
        public virtual MeterGroup MeterGroup { get; set; }
        public virtual OperationalStatu OperationalStatu { get; set; }
        public virtual ParkingSpace ParkingSpace { get; set; }
        public virtual ICollection<SensorMapping> SensorMappings { get; set; }
        public virtual ICollection<SensorPaymentTransaction> SensorPaymentTransactions { get; set; }
        public virtual ICollection<VersionProfileMeter> VersionProfileMeters { get; set; }
        public virtual ICollection<MeterMap> MeterMaps { get; set; }
        public virtual ICollection<SensorPaymentTransactionCurrent> SensorPaymentTransactionCurrents { get; set; }
    }
}
