//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class SensorsAudit
    {
        public long SensorsAuditId { get; set; }
        public int UserId { get; set; }
        public System.DateTime UpdateDateTime { get; set; }
        public int CustomerID { get; set; }
        public int SensorID { get; set; }
        public byte[] BarCodeText { get; set; }
        public string Description { get; set; }
        public string GSMNumber { get; set; }
        public Nullable<long> GlobalMeterID { get; set; }
        public double Latitude { get; set; }
        public double Longitude { get; set; }
        public string Location { get; set; }
        public string SensorName { get; set; }
        public int SensorState { get; set; }
        public Nullable<int> SensorType { get; set; }
        public System.DateTime InstallDateTime { get; set; }
        public Nullable<int> DemandZone { get; set; }
        public string Comments { get; set; }
        public Nullable<int> RoadWayType { get; set; }
        public Nullable<long> ParkingSpaceId { get; set; }
        public Nullable<int> SensorModel { get; set; }
        public Nullable<int> OperationalStatus { get; set; }
        public Nullable<System.DateTime> WarrantyExpiration { get; set; }
        public Nullable<System.DateTime> OperationalStatusTime { get; set; }
        public Nullable<System.DateTime> LastPreventativeMaintenance { get; set; }
        public Nullable<System.DateTime> NextPreventativeMaintenance { get; set; }
        public Nullable<System.DateTime> OperationalStatusEndTime { get; set; }
        public string OperationalStatusComment { get; set; }
        public Nullable<int> AssetPendingReasonId { get; set; }
    
        public virtual AssetPendingReason AssetPendingReason { get; set; }
    }
}
