//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class SensorMapping
    {
        public SensorMapping()
        {
            this.SensorMappingAudits = new HashSet<SensorMappingAudit>();
        }
    
        public int SensorMappingID { get; set; }
        public int CustomerID { get; set; }
        public int SensorID { get; set; }
        public Nullable<long> ParkingSpaceID { get; set; }
        public Nullable<int> GatewayID { get; set; }
        public bool IsPrimaryGateway { get; set; }
        public int MappingState { get; set; }
    
        public virtual AssetState AssetState { get; set; }
        public virtual Gateway Gateway { get; set; }
        public virtual Sensor Sensor { get; set; }
        public virtual ICollection<SensorMappingAudit> SensorMappingAudits { get; set; }
    }
}
