//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class SettledBatch
    {
        public int SettledBatchId { get; set; }
        public int CustomerId { get; set; }
        public Nullable<System.DateTime> StartTs { get; set; }
        public Nullable<System.DateTime> EndTs { get; set; }
        public Nullable<System.DateTime> BatchDate { get; set; }
        public string BatchId { get; set; }
        public Nullable<int> SettleCount { get; set; }
        public Nullable<int> SettleAmtInCent { get; set; }
        public Nullable<int> RefundCount { get; set; }
        public Nullable<int> RefundAmtInCent { get; set; }
        public Nullable<int> UnReconcile { get; set; }
        public Nullable<int> Unidentifiedtransactions { get; set; }
        public Nullable<int> DeclinedCount { get; set; }
        public Nullable<int> DeclinedAmt { get; set; }
        public Nullable<int> UnprocessedCount { get; set; }
        public Nullable<int> UnprocessedAmt { get; set; }
    }
}
