//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class SFPriceSchedule
    {
        public long Id { get; set; }
        public string Feed { get; set; }
        public System.DateTime Received { get; set; }
        public System.DateTime Processed { get; set; }
    }
}
