//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class SLA_RegulatedSchedule
    {
        public long SLA_RegulatedScheduleID { get; set; }
        public int CustomerId { get; set; }
        public int AreaId { get; set; }
        public int MeterId { get; set; }
        public int DayOfWeek { get; set; }
        public int RegulatedStartMinuteOfDay { get; set; }
        public int RegulatedEndMinuteOfDay { get; set; }
        public Nullable<System.DateTime> ScheduleStartDate { get; set; }
        public Nullable<System.DateTime> ScheduleEndDate { get; set; }
    
        public virtual DayOfWeek DayOfWeek1 { get; set; }
        public virtual Meter Meter { get; set; }
    }
}
