//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class sla_AlarmWorkOrder
    {
        public int customerid { get; set; }
        public int areaid { get; set; }
        public int meterid { get; set; }
        public int EventCode { get; set; }
        public int eventsource { get; set; }
        public System.DateTime TimeOfOccurrance { get; set; }
        public Nullable<System.DateTime> TimeOfClearance { get; set; }
        public Nullable<System.DateTime> OccurranceDay { get; set; }
        public Nullable<System.DateTime> ClearanceDay { get; set; }
        public Nullable<int> MaintenanceCode { get; set; }
        public Nullable<int> WorkOrderId { get; set; }
    }
}
