//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class SLA_AssetDownTime
    {
        public long SLA_AssetDownTimeID { get; set; }
        public int CustomerId { get; set; }
        public int AreaId { get; set; }
        public int MeterId { get; set; }
        public int MeterGroup { get; set; }
        public System.DateTime ReportingDate { get; set; }
        public Nullable<int> RegulatedStartMinuteOfDay { get; set; }
        public Nullable<int> RegulatedEndMinuteOfDay { get; set; }
        public Nullable<int> TotalRegulatedMinutes { get; set; }
        public Nullable<int> TotalRegulatedDowntimeMinutes { get; set; }
        public Nullable<int> TotalRegulatedNFFMinutes { get; set; }
        public Nullable<int> RegulatedUpTimePCT { get; set; }
        public Nullable<int> OperationStartMinuteOfDay { get; set; }
        public Nullable<int> OperationEndMinuteOfDay { get; set; }
        public Nullable<int> TotalOperationMinutes { get; set; }
        public Nullable<int> TotalOperationDowntimeMinutes { get; set; }
        public Nullable<int> TotalOperationNFFMinutes { get; set; }
        public Nullable<int> OperationUpTimePC { get; set; }
        public Nullable<int> MaintenanceStartMinuteOfDay { get; set; }
        public Nullable<int> MaintenanceEndMinuteOfDay { get; set; }
        public Nullable<int> TotalMaintenanceMinutes { get; set; }
        public Nullable<int> TotalMaintenanceDowntimeMinutes { get; set; }
        public Nullable<int> TotalMaintenanceNFFMinutes { get; set; }
        public Nullable<int> MaintenanceUpTimePCT { get; set; }
        public Nullable<int> SLAStartTimeMinuteOfDay { get; set; }
        public Nullable<int> SLAEndTimeMinuteOfDay { get; set; }
        public Nullable<int> TotalSLAMinutes { get; set; }
        public Nullable<int> TotalSLADowntimeMinutes { get; set; }
        public Nullable<int> TotalSLANFFMinutes { get; set; }
        public Nullable<int> SLAUpTimePCT { get; set; }
    
        public virtual Meter Meter { get; set; }
    }
}
