//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class SmartCardSerial
    {
        public int SerialNumber { get; set; }
        public int CardTypeID { get; set; }
        public int RegionCode { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<System.DateTime> CreatedTimeStamp { get; set; }
        public string CreatedByUser { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public Nullable<int> TechnicianId { get; set; }
    }
}
