//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class StreetlineEvent
    {
        public int EventId { get; set; }
        public long TransactionId { get; set; }
        public Nullable<int> TypeId { get; set; }
        public int SpaceId { get; set; }
        public int SequenceNum { get; set; }
        public System.DateTime PaymentStartTime { get; set; }
        public System.DateTime PaymentExpiryTime { get; set; }
        public Nullable<System.DateTime> ResponseTime { get; set; }
        public Nullable<int> Amount { get; set; }
        public int CustomerId { get; set; }
        public int attempt { get; set; }
    }
}
