//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubArea
    {
        public SubArea()
        {
            this.SubAreaSeqs = new HashSet<SubAreaSeq>();
            this.MeterMaps = new HashSet<MeterMap>();
        }
    
        public int CustomerID { get; set; }
        public int SubAreaID { get; set; }
        public string SubAreaName { get; set; }
        public string Description { get; set; }
        public Nullable<int> ParentAreaID { get; set; }
        public Nullable<int> SubAreaState { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ICollection<SubAreaSeq> SubAreaSeqs { get; set; }
        public virtual ICollection<MeterMap> MeterMaps { get; set; }
    }
}
