//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class TargetServiceDesignation
    {
        public TargetServiceDesignation()
        {
            this.HistoricalAlarms = new HashSet<HistoricalAlarm>();
        }
    
        public int TargetServiceDesignationId { get; set; }
        public string TargetServiceDesignationDesc { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<bool> IsDisplay { get; set; }
    
        public virtual ICollection<HistoricalAlarm> HistoricalAlarms { get; set; }
    }
}
