//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class TariffState
    {
        public TariffState()
        {
            this.HolidayRateConfigurations = new HashSet<HolidayRateConfiguration>();
            this.RateScheduleConfigurations = new HashSet<RateScheduleConfiguration>();
            this.TariffRateConfigurations = new HashSet<TariffRateConfiguration>();
        }
    
        public int TariffStateId { get; set; }
        public string TariffStateDesc { get; set; }
    
        public virtual ICollection<HolidayRateConfiguration> HolidayRateConfigurations { get; set; }
        public virtual ICollection<RateScheduleConfiguration> RateScheduleConfigurations { get; set; }
        public virtual ICollection<TariffRateConfiguration> TariffRateConfigurations { get; set; }
    }
}
