//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class TariffRate
    {
        public TariffRate()
        {
            this.TariffRate1 = new HashSet<TariffRate>();
            this.TariffRateForConfigurations = new HashSet<TariffRateForConfiguration>();
        }
    
        public long TariffRateId { get; set; }
        public int CustomerId { get; set; }
        public string RateName { get; set; }
        public int RateInCents { get; set; }
        public Nullable<int> PerTimeValue { get; set; }
        public Nullable<int> PerTimeUnit { get; set; }
        public Nullable<int> MaxTimeValue { get; set; }
        public Nullable<int> MaxTimeUnit { get; set; }
        public Nullable<int> GracePeriodMinute { get; set; }
        public Nullable<long> LinkedRate { get; set; }
        public string RateDesc { get; set; }
        public Nullable<bool> LockMaxTime { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<TariffRate> TariffRate1 { get; set; }
        public virtual TariffRate TariffRate2 { get; set; }
        public virtual TimeUnit TimeUnit { get; set; }
        public virtual TimeUnit TimeUnit1 { get; set; }
        public virtual ICollection<TariffRateForConfiguration> TariffRateForConfigurations { get; set; }
    }
}
