//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class TccDeclinedBuffer
    {
        public int ID { get; set; }
        public int CustomerId { get; set; }
        public long TccId { get; set; }
        public string HCardNum { get; set; }
        public string XCardNum { get; set; }
        public System.DateTime DeclinedTS { get; set; }
    }
}
