//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class TechCreditEvent
    {
        public long EventId { get; set; }
        public int CustomerId { get; set; }
        public int AreaId { get; set; }
        public int MeterId { get; set; }
        public System.DateTime EventDateTime { get; set; }
        public int BayStart { get; set; }
        public int BayEnd { get; set; }
        public string Note { get; set; }
        public Nullable<int> TechnicianKeyID { get; set; }
        public Nullable<long> EventUID { get; set; }
    
        public virtual Meter Meter { get; set; }
    }
}
