//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeUnit
    {
        public TimeUnit()
        {
            this.TariffRates = new HashSet<TariffRate>();
            this.TariffRates1 = new HashSet<TariffRate>();
        }
    
        public int TimeUnitId { get; set; }
        public string TimeUnitDesc { get; set; }
    
        public virtual ICollection<TariffRate> TariffRates { get; set; }
        public virtual ICollection<TariffRate> TariffRates1 { get; set; }
    }
}
