//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeZone
    {
        public TimeZone()
        {
            this.Customers = new HashSet<Customer>();
            this.Gateways = new HashSet<Gateway>();
            this.Meters = new HashSet<Meter>();
        }
    
        public int TimeZoneID { get; set; }
        public int LocalTimeUTCDifference { get; set; }
        public int DaylightSavingAdjustment { get; set; }
        public System.DateTime UTCSummerTimeStart { get; set; }
        public System.DateTime UTCSummerTimeEnd { get; set; }
        public string TimeZoneName { get; set; }
    
        public virtual ICollection<Customer> Customers { get; set; }
        public virtual ICollection<Gateway> Gateways { get; set; }
        public virtual ICollection<Meter> Meters { get; set; }
    }
}
