//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionsBlackList
    {
        public Nullable<long> GlobalMeterId { get; set; }
        public int CustomerId { get; set; }
        public int AreaId { get; set; }
        public int MeterId { get; set; }
        public System.DateTime TransDateTime { get; set; }
        public Nullable<int> ReceiptNo { get; set; }
        public Nullable<int> BayNumber { get; set; }
        public Nullable<int> AmountInCents { get; set; }
        public Nullable<int> TimePaid { get; set; }
        public int TransType { get; set; }
        public string CardNumHash { get; set; }
        public int CreditCardType { get; set; }
    
        public virtual Meter Meter { get; set; }
    }
}
