//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionsMPark
    {
        public long TransactionsMParkID { get; set; }
        public Nullable<long> ParkingSpaceId { get; set; }
        public int CustomerID { get; set; }
        public int AreaID { get; set; }
        public int MeterId { get; set; }
        public System.DateTime TransDateTime { get; set; }
        public long TransactionID { get; set; }
        public int BayNumber { get; set; }
        public int AmountInCents { get; set; }
        public int TimePaid { get; set; }
        public int UserType { get; set; }
        public Nullable<System.DateTime> OriginateDateTime { get; set; }
        public Nullable<long> UserCLI { get; set; }
        public Nullable<long> ReconFileID { get; set; }
        public Nullable<System.DateTime> ReconDateTime { get; set; }
        public Nullable<int> NumberOfMinutes { get; set; }
        public Nullable<int> TimePaidByRate { get; set; }
        public Nullable<int> VendorId { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> CreateDateTime { get; set; }
    
        public virtual Meter Meter { get; set; }
        public virtual ParkingSpace ParkingSpace { get; set; }
        public virtual TransUserType TransUserType { get; set; }
    }
}
