//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransDataSumm
    {
        public Nullable<long> GlobalMeterId { get; set; }
        public int CustomerId { get; set; }
        public int AreaId { get; set; }
        public int MeterId { get; set; }
        public Nullable<System.DateTime> CollDateTimeCash { get; set; }
        public Nullable<System.DateTime> CollDateTimeCredCard { get; set; }
        public Nullable<System.DateTime> CollDateTimeSmtCard { get; set; }
        public Nullable<System.DateTime> CollDateTimeOtherMthd { get; set; }
        public Nullable<double> AmountCash { get; set; }
        public Nullable<double> AmountCredCard { get; set; }
        public Nullable<double> AmountSmtCard { get; set; }
        public Nullable<double> AmountOtherMthd { get; set; }
        public Nullable<int> NoOfTransCash { get; set; }
        public Nullable<int> NoOfTransCredCard { get; set; }
        public Nullable<int> NoOfTransSmtCard { get; set; }
        public Nullable<int> NoOfTransOtherMthd { get; set; }
        public Nullable<int> PackageIdCash { get; set; }
        public Nullable<int> PackageIdCredCard { get; set; }
        public Nullable<int> PackageIdSmtCard { get; set; }
        public Nullable<int> PackageIdOtherMthd { get; set; }
    
        public virtual Meter Meter { get; set; }
    }
}
