//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionsCreditCard
    {
        public long TransactionsCreditCardID { get; set; }
        public Nullable<long> ParkingSpaceId { get; set; }
        public int CustomerId { get; set; }
        public int AreaId { get; set; }
        public int MeterId { get; set; }
        public System.DateTime TransDateTime { get; set; }
        public int ReceiptNo { get; set; }
        public Nullable<int> BayNumber { get; set; }
        public int AmountInCents { get; set; }
        public Nullable<int> TimePaid { get; set; }
        public int Status { get; set; }
        public string CardNumHash { get; set; }
        public Nullable<int> CreditCardType { get; set; }
        public string XSwipeData { get; set; }
        public string AcquirerTransReference { get; set; }
        public string PaymentTarget { get; set; }
        public Nullable<int> CashKeySrID { get; set; }
        public Nullable<int> CashKeyBalanceBefore { get; set; }
        public string BatchId { get; set; }
        public Nullable<bool> Reconciled { get; set; }
        public Nullable<System.DateTime> ResultDateTime { get; set; }
        public int HashScheme { get; set; }
        public Nullable<int> TimePaidByRate { get; set; }
        public Nullable<int> OLTStatusCode { get; set; }
        public Nullable<int> OLTOriginalStatusCode { get; set; }
        public Nullable<int> OLTCardBalance { get; set; }
        public string Track64 { get; set; }
        public Nullable<System.DateTime> CreateDateTime { get; set; }
        public Nullable<int> DiscountInCent { get; set; }
        public Nullable<int> DiscountSchemeId { get; set; }
        public string Last4 { get; set; }
        public Nullable<bool> PrepayUsed { get; set; }
        public Nullable<bool> FreeParkingUsed { get; set; }
        public Nullable<bool> TopUp { get; set; }
        public Nullable<int> DiscountrejectInCent { get; set; }
        public Nullable<int> GatewayMethod { get; set; }
        public Nullable<long> ParkAndSwimLink { get; set; }
        public string SettleBatchID { get; set; }
    
        public virtual CreditCardType CreditCardType1 { get; set; }
        public virtual DiscountScheme DiscountScheme { get; set; }
        public virtual Meter Meter { get; set; }
        public virtual ParkingSpace ParkingSpace { get; set; }
        public virtual PaymentTargetType PaymentTargetType { get; set; }
        public virtual TransactionStatu TransactionStatu { get; set; }
    }
}
