//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionsReconcile
    {
        public Nullable<long> GlobalMeterId { get; set; }
        public int CustomerID { get; set; }
        public int AreaId { get; set; }
        public int MeterId { get; set; }
        public int ReceiptNo { get; set; }
        public Nullable<System.DateTime> TransDateTime { get; set; }
        public long TransactionID { get; set; }
        public int CardTypeCode { get; set; }
    
        public virtual CardType CardType { get; set; }
    }
}
