//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransUserType
    {
        public TransUserType()
        {
            this.TransactionsMParks = new HashSet<TransactionsMPark>();
        }
    
        public int UserType { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<TransactionsMPark> TransactionsMParks { get; set; }
    }
}
