//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionBatch
    {
        public long TransactionBatchId { get; set; }
        public long TransactionID { get; set; }
        public string BatchRef { get; set; }
        public int Status { get; set; }
    }
}
