//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class txbackup
    {
        public long TransactionsID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> AreaID { get; set; }
        public Nullable<int> MeterID { get; set; }
        public Nullable<int> ZoneID { get; set; }
        public Nullable<long> ParkingSpaceID { get; set; }
        public Nullable<int> SensorID { get; set; }
        public Nullable<int> TransactionType { get; set; }
        public Nullable<System.DateTime> TransDateTime { get; set; }
        public Nullable<System.DateTime> ExpiryTime { get; set; }
        public Nullable<int> AmountInCents { get; set; }
        public string TxValue { get; set; }
        public Nullable<int> TimePaid { get; set; }
        public Nullable<int> TimeType1 { get; set; }
        public Nullable<int> TimeType2 { get; set; }
        public Nullable<int> TimeType3 { get; set; }
        public Nullable<int> TimeType4 { get; set; }
        public Nullable<int> TimeType5 { get; set; }
        public Nullable<long> EventUID { get; set; }
        public Nullable<int> BayNumber { get; set; }
        public Nullable<int> CreditCardType { get; set; }
        public Nullable<int> TransactionStatus { get; set; }
        public Nullable<int> ReceiptNo { get; set; }
        public Nullable<long> OriginalTxId { get; set; }
        public Nullable<int> TransType { get; set; }
        public Nullable<int> MeterGroupId { get; set; }
        public Nullable<int> GatewayId { get; set; }
        public Nullable<long> SensorPaymentTransactionId { get; set; }
        public Nullable<bool> PrepayUsed { get; set; }
        public Nullable<bool> FreeParkingUsed { get; set; }
        public Nullable<int> DiscountSchemeId { get; set; }
    }
}
