//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_ActiveCollectionRunMeter
    {
        public Nullable<int> CustomerId { get; set; }
        public int AreaId { get; set; }
        public int MeterId { get; set; }
        public Nullable<System.DateTime> ActivationDate { get; set; }
        public Nullable<System.DateTime> ExipryDate { get; set; }
        public long CollectionRunId { get; set; }
        public int CollectionRunStatus { get; set; }
    }
}
