//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_UnProcessed_CollRun
    {
        public long CollectionRunId { get; set; }
        public string CollectionRunName { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> LastEdited { get; set; }
        public Nullable<int> LastEditedBy { get; set; }
        public Nullable<System.DateTime> ActivationDate { get; set; }
        public Nullable<int> DaysBetweenCol { get; set; }
        public Nullable<bool> SkipPublicHolidays { get; set; }
        public Nullable<bool> SkipSpecificDaysOfWeek { get; set; }
        public int CollectionRunStatus { get; set; }
        public Nullable<int> VendorId { get; set; }
        public bool SkipSpecificDaysOfWeekSunday { get; set; }
        public bool SkipSpecificDaysOfWeekMonday { get; set; }
        public bool SkipSpecificDaysOfWeekTuesday { get; set; }
        public bool SkipSpecificDaysOfWeekWednesday { get; set; }
        public bool SkipSpecificDaysOfWeekThursday { get; set; }
        public bool SkipSpecificDaysOfWeekFriday { get; set; }
        public bool SkipSpecificDaysOfWeekSaturday { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public Nullable<int> CustomerId { get; set; }
    }
}
