//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class VersionProfileMeter
    {
        public VersionProfileMeter()
        {
            this.VersionProfileMeterAudits = new HashSet<VersionProfileMeterAudit>();
        }
    
        public long VersionProfileMeterId { get; set; }
        public string ConfigurationName { get; set; }
        public string HardwareVersion { get; set; }
        public string SoftwareVersion { get; set; }
        public string CommunicationVersion { get; set; }
        public string Version1 { get; set; }
        public string Version2 { get; set; }
        public string Version3 { get; set; }
        public string Version4 { get; set; }
        public string Version5 { get; set; }
        public string Version6 { get; set; }
        public int CustomerId { get; set; }
        public Nullable<int> AreaId { get; set; }
        public Nullable<int> MeterId { get; set; }
        public int MeterGroup { get; set; }
        public Nullable<int> SensorID { get; set; }
        public Nullable<int> GatewayID { get; set; }
    
        public virtual Gateway Gateway { get; set; }
        public virtual MeterGroup MeterGroup1 { get; set; }
        public virtual Meter Meter { get; set; }
        public virtual Sensor Sensor { get; set; }
        public virtual ICollection<VersionProfileMeterAudit> VersionProfileMeterAudits { get; set; }
    }
}
