//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViolationSummaryV
    {
        public System.DateTime IssueDateTime { get; set; }
        public int ParkingViosId { get; set; }
        public int CustomerID { get; set; }
        public Nullable<int> ParkingId { get; set; }
        public string VioCode { get; set; }
        public string VioDescription { get; set; }
        public int OfficerId { get; set; }
        public string OfficerName { get; set; }
        public string Agency { get; set; }
        public string Beat { get; set; }
        public string LocBlock { get; set; }
        public string LocLot { get; set; }
        public string LocStreet { get; set; }
        public float VioFine { get; set; }
        public float VioLateFee { get; set; }
        public Nullable<double> FineTotal { get; set; }
        public Nullable<double> FineTotalPerc { get; set; }
        public Nullable<int> VALID { get; set; }
        public Nullable<int> VALIDPERC { get; set; }
        public Nullable<int> VOID { get; set; }
        public Nullable<int> VOIDPERC { get; set; }
    }
}
