//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class VoidReasonSummaryV
    {
        public int ParkingId { get; set; }
        public System.DateTime IssueDateTime { get; set; }
        public long IssueNo { get; set; }
        public string VoidStatus { get; set; }
        public Nullable<System.DateTime> VoidStatusDate { get; set; }
        public string VoidReason { get; set; }
        public string VoidedInField { get; set; }
        public string Reissued { get; set; }
        public Nullable<int> OfficerID { get; set; }
        public string OfficerName { get; set; }
        public string Agency { get; set; }
        public string Beat { get; set; }
        public Nullable<int> CustomerID { get; set; }
    }
}
