//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class WhiteListFile_Unique
    {
        public long ID { get; set; }
        public int CustomerId { get; set; }
        public int AreaId { get; set; }
        public int MeterId { get; set; }
        public string CardHash { get; set; }
        public int DiscountSchemeId { get; set; }
        public int DiscountPercentage { get; set; }
        public int DiscountMinute { get; set; }
        public int MaxAmountInCents { get; set; }
        public string Delta { get; set; }
    }
}
