//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkOrderStatu
    {
        public WorkOrderStatu()
        {
            this.WorkOrders = new HashSet<WorkOrder1>();
        }
    
        public int WorkOrderStatusId { get; set; }
        public string WorkORderStatusDesc { get; set; }
    
        public virtual ICollection<WorkOrder1> WorkOrders { get; set; }
    }
}
