//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkOrder
    {
        public WorkOrder()
        {
            this.WorkOrderCallers = new HashSet<WorkOrderCaller>();
        }
    
        public int WorkOrderId { get; set; }
        public int CustomerID { get; set; }
        public int AssignedBy { get; set; }
        public System.DateTime AssignedTS { get; set; }
        public Nullable<int> TechnicianID { get; set; }
    
        public virtual ICollection<WorkOrderCaller> WorkOrderCallers { get; set; }
    }
}
