//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.PEMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkOrderCaller
    {
        public int WorkOrderCallerId { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> WorkOrderID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string LicensePlate { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual WorkOrder WorkOrder { get; set; }
    }
}
