//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportQuery
    {
        public int Id { get; set; }
        public int ReportId { get; set; }
        public int CustomerId { get; set; }
        public string Query { get; set; }
    
        public virtual CustomerProfile CustomerProfile { get; set; }
        public virtual ReportType ReportType { get; set; }
    }
}
