//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.Web.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://aidev.duncan-usa.com/ReinoWebServices/US_DEMO_AAutoISSUEHost/AutoISSUEHost" +
            "Service.asmx")]
        public string Duncan_PEMS_Web_AutoIssueSvc_AutoISSUEHostService {
            get {
                return ((string)(this["Duncan_PEMS_Web_AutoIssueSvc_AutoISSUEHostService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://aipro05.duncan-usa.com/ReinoWebServices/New%20OrleansAutoISSUEHost/AutoISS" +
            "UEHostService.asmx")]
        public string Duncan_PEMS_Web_AutoIssueSvcNewOrleans_AutoISSUEHostService {
            get {
                return ((string)(this["Duncan_PEMS_Web_AutoIssueSvcNewOrleans_AutoISSUEHostService"]));
            }
        }
    }
}
