//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.OracleDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACTIVITYLOG
    {
        public Nullable<System.DateTime> STARTDATE { get; set; }
        public Nullable<System.DateTime> STARTTIME { get; set; }
        public Nullable<System.DateTime> ENDDATE { get; set; }
        public Nullable<System.DateTime> ENDTIME { get; set; }
        public string OFFICERNAME { get; set; }
        public string OFFICERID { get; set; }
        public string PRIMARYACTIVITYNAME { get; set; }
        public Nullable<short> PRIMARYACTIVITYCOUNT { get; set; }
        public string SECONDARYACTIVITYNAME { get; set; }
        public Nullable<short> SECONDARYACTIVITYCOUNT { get; set; }
        public string EXTRAPROMPT1 { get; set; }
        public string EXTRADATA1 { get; set; }
        public string EXTRAPROMPT2 { get; set; }
        public string EXTRADATA2 { get; set; }
        public string EXTRAPROMPT3 { get; set; }
        public string EXTRADATA3 { get; set; }
        public int UNIQUEKEY { get; set; }
        public Nullable<System.DateTime> RECCREATIONDATE { get; set; }
        public string RECOVEREDBYHH { get; set; }
        public Nullable<int> FORMREV { get; set; }
        public string FORMNAME { get; set; }
        public Nullable<int> TABLEREV { get; set; }
        public Nullable<System.DateTime> STANDARDEXPORTDATE { get; set; }
        public Nullable<int> REINOROWVERSION { get; set; }
        public Nullable<int> SUBCONFIGKEY { get; set; }
        public Nullable<int> TBLENCRYPTVERSION { get; set; }
        public Nullable<int> ENCRYPTIONKEYID { get; set; }
        public Nullable<int> TRANSACTIONKEY { get; set; }
        public string TRANSACTIONNAME { get; set; }
        public Nullable<System.DateTime> USERDEF1EXPORTDATE { get; set; }
        public Nullable<System.DateTime> USERDEF2EXPORTDATE { get; set; }
        public Nullable<System.DateTime> USERDEF3EXPORTDATE { get; set; }
        public Nullable<System.DateTime> USERDEF4EXPORTDATE { get; set; }
        public Nullable<System.DateTime> USERDEF5EXPORTDATE { get; set; }
        public Nullable<System.DateTime> CUSTOM1EXPORTDATE { get; set; }
        public Nullable<System.DateTime> CUSTOM2EXPORTDATE { get; set; }
        public Nullable<System.DateTime> CUSTOM3EXPORTDATE { get; set; }
        public Nullable<System.DateTime> WIRELESSEXPORTDATE_AUTOPROC { get; set; }
        public Nullable<int> AUTOPROC_UNIQUEKEY { get; set; }
        public Nullable<decimal> START_LOCLATITUDE { get; set; }
        public Nullable<decimal> START_LOCLONGITUDE { get; set; }
        public Nullable<decimal> END_LOCLATITUDE { get; set; }
        public Nullable<decimal> END_LOCLONGITUDE { get; set; }
        public string UNITSERIAL { get; set; }
    }
}
