//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.OracleDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARKNOTE
    {
        public int MASTERKEY { get; set; }
        public Nullable<short> DETAILRECNO { get; set; }
        public Nullable<System.DateTime> NOTEDATE { get; set; }
        public Nullable<System.DateTime> NOTETIME { get; set; }
        public string OFFICERNAME { get; set; }
        public string OFFICERID { get; set; }
        public Nullable<System.DateTime> RECCREATIONDATE { get; set; }
        public Nullable<System.DateTime> RECCREATIONTIME { get; set; }
        public string NOTESMEMO { get; set; }
        public string DIAGRAM { get; set; }
        public string MULTIMEDIANOTEDATATYPE { get; set; }
        public string MULTIMEDIANOTEFILENAME { get; set; }
        public Nullable<System.DateTime> MULTIMEDIANOTEFILEDATESTAMP { get; set; }
        public Nullable<System.DateTime> MULTIMEDIANOTEFILETIMESTAMP { get; set; }
        public int UNIQUEKEY { get; set; }
        public string RECOVEREDBYHH { get; set; }
        public Nullable<int> FORMREV { get; set; }
        public string FORMNAME { get; set; }
        public Nullable<int> TABLEREV { get; set; }
        public Nullable<System.DateTime> STANDARDEXPORTDATE { get; set; }
        public Nullable<int> REINOROWVERSION { get; set; }
        public Nullable<int> SUBCONFIGKEY { get; set; }
        public Nullable<int> TBLENCRYPTVERSION { get; set; }
        public Nullable<int> ENCRYPTIONKEYID { get; set; }
        public byte[] MULTIMEDIANOTEDATA { get; set; }
        public string PRINTEDIMAGEORDER { get; set; }
        public Nullable<int> TRANSACTIONKEY { get; set; }
        public string TRANSACTIONNAME { get; set; }
        public Nullable<System.DateTime> USERDEF1EXPORTDATE { get; set; }
        public Nullable<System.DateTime> USERDEF2EXPORTDATE { get; set; }
        public Nullable<System.DateTime> USERDEF3EXPORTDATE { get; set; }
        public Nullable<System.DateTime> USERDEF4EXPORTDATE { get; set; }
        public Nullable<System.DateTime> USERDEF5EXPORTDATE { get; set; }
        public Nullable<System.DateTime> CUSTOM1EXPORTDATE { get; set; }
        public Nullable<System.DateTime> CUSTOM2EXPORTDATE { get; set; }
        public Nullable<System.DateTime> CUSTOM3EXPORTDATE { get; set; }
        public Nullable<System.DateTime> WIRELESSEXPORTDATE_AUTOPROC { get; set; }
        public Nullable<int> AUTOPROC_UNIQUEKEY { get; set; }
    }
}
