//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.OracleDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARKING
    {
        public Nullable<System.DateTime> ISSUEDATE { get; set; }
        public string PLATECHECKDIGIT { get; set; }
        public Nullable<System.DateTime> ISSUETIME { get; set; }
        public string ISSUENOPFX { get; set; }
        public Nullable<decimal> ISSUENO { get; set; }
        public string ISSUENOSFX { get; set; }
        public Nullable<System.DateTime> DUEDATE { get; set; }
        public string DUEDATE2 { get; set; }
        public Nullable<System.DateTime> DUEDATE3 { get; set; }
        public string OFFICERNAME { get; set; }
        public string OFFICERID { get; set; }
        public string AGENCY { get; set; }
        public string LOCMETER { get; set; }
        public string LOCLOT { get; set; }
        public string LOCBLOCK { get; set; }
        public string LOCSTREET { get; set; }
        public string LOCCROSSSTREET1 { get; set; }
        public string LOCCROSSSTREET2 { get; set; }
        public string METERNO { get; set; }
        public string VEHLICNO { get; set; }
        public string VEHLICSTATE { get; set; }
        public Nullable<System.DateTime> VEHLICEXPDATE { get; set; }
        public string VEHLICTYPE { get; set; }
        public string VEHVIN { get; set; }
        public string VEHMAKE { get; set; }
        public string VEHMODEL { get; set; }
        public string VEHBODYSTYLE { get; set; }
        public string VEHCOLOR1 { get; set; }
        public string VEHCOLOR2 { get; set; }
        public string REMARK1 { get; set; }
        public string REMARK2 { get; set; }
        public Nullable<short> FORMREV { get; set; }
        public string DIRECTION { get; set; }
        public string PERMITNO { get; set; }
        public string ISWARNING { get; set; }
        public string NOTE1 { get; set; }
        public string NOTE2 { get; set; }
        public string WARNINGREMARK { get; set; }
        public string AGENCYDESIGNATOR { get; set; }
        public string LOCSPACE { get; set; }
        public Nullable<decimal> ESCALATEDFINE { get; set; }
        public Nullable<decimal> ESCALATEDLATEFEE { get; set; }
        public string ESCALATIONCOUNT { get; set; }
        public string COURTAPPDATE { get; set; }
        public Nullable<System.DateTime> COURTTIME { get; set; }
        public string VEHLICCD { get; set; }
        public string VEHLICTYPECODE { get; set; }
        public string VEHTYPE { get; set; }
        public string PERMIT { get; set; }
        public string OFFICERSIGNATURE { get; set; }
        public int UNIQUEKEY { get; set; }
        public Nullable<System.DateTime> RECCREATIONDATE { get; set; }
        public string RECOVEREDBYHH { get; set; }
        public string FORMNAME { get; set; }
        public Nullable<int> TABLEREV { get; set; }
        public Nullable<System.DateTime> STANDARDEXPORTDATE { get; set; }
        public Nullable<int> REINOROWVERSION { get; set; }
        public Nullable<int> SUBCONFIGKEY { get; set; }
        public Nullable<int> TBLENCRYPTVERSION { get; set; }
        public Nullable<int> ENCRYPTIONKEYID { get; set; }
        public Nullable<int> TRANSACTIONKEY { get; set; }
        public string TRANSACTIONNAME { get; set; }
        public Nullable<decimal> FRMANDSTRREV { get; set; }
        public string UNITSERIAL { get; set; }
        public string ISSUENOCHKDGT { get; set; }
        public string VOIDSTATUS { get; set; }
        public Nullable<System.DateTime> VOIDSTATUSDATE { get; set; }
        public string VOIDREASON { get; set; }
        public string VOIDEDINFIELD { get; set; }
        public string REISSUED { get; set; }
        public Nullable<System.DateTime> USERDEF1EXPORTDATE { get; set; }
        public Nullable<System.DateTime> USERDEF2EXPORTDATE { get; set; }
        public Nullable<System.DateTime> USERDEF3EXPORTDATE { get; set; }
        public Nullable<System.DateTime> USERDEF4EXPORTDATE { get; set; }
        public Nullable<System.DateTime> USERDEF5EXPORTDATE { get; set; }
        public Nullable<System.DateTime> CUSTOM1EXPORTDATE { get; set; }
        public Nullable<System.DateTime> CUSTOM2EXPORTDATE { get; set; }
        public Nullable<System.DateTime> CUSTOM3EXPORTDATE { get; set; }
        public Nullable<System.DateTime> WIRELESSEXPORTDATE_AUTOPROC { get; set; }
        public Nullable<int> AUTOPROC_UNIQUEKEY { get; set; }
        public string BEAT { get; set; }
        public string LOCDESCRIPTOR { get; set; }
        public Nullable<decimal> LOCLATITUDE { get; set; }
        public Nullable<decimal> LOCLONGITUDE { get; set; }
        public string VEHVIN4 { get; set; }
        public string SHIFT { get; set; }
        public string SQUAD { get; set; }
        public Nullable<System.DateTime> HEARINGDATE { get; set; }
        public string HEARINGTIME { get; set; }
        public string LOCDIRECTION { get; set; }
        public string REMARK3 { get; set; }
        public string ENF_METERID { get; set; }
        public string ENF_METERSCANDATETIME { get; set; }
        public string ENF_METERRTCDATETIME { get; set; }
        public string ENF_METERLUTDATETIME { get; set; }
        public string ENF_METERMODE { get; set; }
        public string ENF_METERCLUSTERID { get; set; }
        public string ENF_METERCLUSTERMEMBERS { get; set; }
        public string ENF_BAYEXPIREDMINUTES { get; set; }
        public string ENF_BAYSTATUSCODE { get; set; }
        public string ENF_BAYSTATECODE { get; set; }
        public string ENF_HANDHELDMODE { get; set; }
        public string ENF_METERBAYNO { get; set; }
        public string ENF_METERID_INTERNAL { get; set; }
        public string ENF_METERBAYNO_INTERNAL { get; set; }
        public string ENF_METER_TYPE { get; set; }
        public Nullable<decimal> REINO_DATA_AGE { get; set; }
        public string REINO_CONFIRMATION_CODE { get; set; }
        public string REINO_METER_ID { get; set; }
        public string PBC_ENF_ZONEID { get; set; }
        public string PBC_ENF_LICPLATE { get; set; }
        public string PBC_ENF_LICSTATE { get; set; }
        public string PBC_ENF_REASON { get; set; }
        public string PBC_DATA_AGE { get; set; }
        public string PBC_CONFIRMATION_CODE { get; set; }
    }
}
