//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.OracleDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SECURITY_USER
    {
        public int UNIQUEKEY { get; set; }
        public string USERNAME { get; set; }
        public string OFFICERNAME { get; set; }
        public string OFFICERID { get; set; }
        public string OFFICERREINOTECHKEY { get; set; }
        public string SALT { get; set; }
        public string SALTEDHASH { get; set; }
        public string HASHBROWN { get; set; }
        public Nullable<System.DateTime> RECCREATIONDATE { get; set; }
        public Nullable<System.DateTime> PWDCHANGED { get; set; }
        public Nullable<System.DateTime> LASTLOGIN { get; set; }
        public Nullable<System.DateTime> PWDEXPIRATION { get; set; }
        public Nullable<System.DateTime> LOCKOUTTIME { get; set; }
        public Nullable<System.DateTime> LASTREMINDER { get; set; }
        public Nullable<int> FAILEDLOGINS { get; set; }
        public string NETWORKDOMAIN1 { get; set; }
        public string NETWORKUSERNAME1 { get; set; }
        public string NETWORKPASSWORD1 { get; set; }
        public string NETWORKDOMAIN2 { get; set; }
        public string NETWORKUSERNAME2 { get; set; }
        public string NETWORKPASSWORD2 { get; set; }
        public string NETWORKDOMAIN3 { get; set; }
        public string NETWORKUSERNAME3 { get; set; }
        public string NETWORKPASSWORD3 { get; set; }
        public string NETWORKDOMAIN4 { get; set; }
        public string NETWORKUSERNAME4 { get; set; }
        public string NETWORKPASSWORD4 { get; set; }
    }
}
