//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.RBAC
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerReport
    {
        public int CustomerReportId { get; set; }
        public int CustomerId { get; set; }
        public int CustomerReportsCategoryId { get; set; }
        public string ReportAction { get; set; }
        public string Host { get; set; }
        public string Path { get; set; }
        public string Parameters { get; set; }
    
        public virtual CustomerReportsCategory CustomerReportsCategory { get; set; }
    }
}
