//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.RBAC
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerType
    {
        public CustomerType()
        {
            this.CustomerProfiles = new HashSet<CustomerProfile>();
        }
    
        public int CustomerTypeId { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<CustomerProfile> CustomerProfiles { get; set; }
    }
}
