//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.RBAC
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerSettingType
    {
        public CustomerSettingType()
        {
            this.CustomerSettings = new HashSet<CustomerSetting>();
            this.CustomerSettingsGroupMembers = new HashSet<CustomerSettingsGroupMember>();
            this.CustomerSettingTypeLists = new HashSet<CustomerSettingTypeList>();
        }
    
        public int CustomerSettingTypeId { get; set; }
        public string CustomerSettingTypeName { get; set; }
        public int SettingTypeId { get; set; }
        public bool IsRequired { get; set; }
        public string DefaultValue { get; set; }
        public string InternalValue { get; set; }
    
        public virtual ICollection<CustomerSetting> CustomerSettings { get; set; }
        public virtual ICollection<CustomerSettingsGroupMember> CustomerSettingsGroupMembers { get; set; }
        public virtual ICollection<CustomerSettingTypeList> CustomerSettingTypeLists { get; set; }
    }
}
