//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.RBAC
{
    using System;
    using System.Collections.Generic;
    
    public partial class FMWorkOrdersAudit
    {
        public long WorkOrderAuditId { get; set; }
        public System.DateTime AuditDateTime { get; set; }
        public Nullable<int> UserId { get; set; }
        public long WorkOrderId { get; set; }
        public Nullable<int> ReportingUserId { get; set; }
        public int MeterGroup { get; set; }
        public int CustomerId { get; set; }
        public int AreaId { get; set; }
        public int MeterId { get; set; }
        public string Location { get; set; }
        public Nullable<long> ParkingSpaceId { get; set; }
        public string Notes { get; set; }
        public Nullable<int> ZoneId { get; set; }
        public int HighestSeverity { get; set; }
        public System.DateTime CreateDateTime { get; set; }
        public System.DateTime SLADue { get; set; }
        public int Status { get; set; }
        public Nullable<int> TechnicianId { get; set; }
        public Nullable<System.DateTime> AssignedDate { get; set; }
        public Nullable<System.DateTime> CompletedDate { get; set; }
        public Nullable<int> CreatedById { get; set; }
        public string CrossStreet { get; set; }
        public Nullable<int> ResolutionCode { get; set; }
        public string ResolutionDesc { get; set; }
        public Nullable<int> AssignmentState { get; set; }
        public Nullable<int> Mechanism { get; set; }
    
        public virtual FMWorkOrder WorkOrder { get; set; }        
    }
}
