//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.RBAC
{
    using System;
    using System.Collections.Generic;
    
    public partial class FMWorkOrderPart
    {
        public long WorkOrderPartId { get; set; }
        public long WorkOrderId { get; set; }
        public long PartId { get; set; }
        public int Quantity { get; set; }
        public string Notes { get; set; }
    
        public virtual FMPart Part { get; set; }
        public virtual FMWorkOrder WorkOrder { get; set; }        
    }
}
