//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.RBAC
{
    using System;
    using System.Collections.Generic;
    
    public partial class FMWorkOrderImage
    {
        public long WorkOrderImageId { get; set; }
        public long WorkOrderId { get; set; }
        public byte[] ImageData { get; set; }
        public System.DateTime DateTaken { get; set; }
    
        public virtual FMWorkOrder WorkOrder { get; set; }        
    }
}
