//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.RBAC
{
    using System;
    using System.Collections.Generic;
    
    public partial class FMWorkOrderStatu
    {
        public FMWorkOrderStatu()
        {
            this.WorkOrders = new HashSet<FMWorkOrder>();            
        }
    
        public int WorkOrderStatusId { get; set; }
        public string WorkOrderStatusDesc { get; set; }
    
        public virtual ICollection<FMWorkOrder> WorkOrders { get; set; }        
    }
}
