//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.RBAC
{
    using System;
    using System.Collections.Generic;
    
    public partial class FMWorkOrder1
    {
        public FMWorkOrder1()
        {
            this.WorkOrderEvents = new HashSet<FMWorkOrderEvent>();
            this.WorkOrderImages = new HashSet<FMWorkOrderImage>();
            this.WorkOrderParts = new HashSet<FMWorkOrderPart>();
            this.WorkOrdersAudits = new HashSet<FMWorkOrdersAudit>();
        }
    
        public long WorkOrderId { get; set; }
        public Nullable<int> ReportingUserId { get; set; }
        public int MeterGroup { get; set; }
        public int CustomerId { get; set; }
        public int AreaId { get; set; }
        public int MeterId { get; set; }
        public string Location { get; set; }
        public Nullable<long> ParkingSpaceId { get; set; }
        public string Notes { get; set; }
        public Nullable<int> ZoneId { get; set; }
        public int HighestSeverity { get; set; }
        public System.DateTime CreateDateTime { get; set; }
        public System.DateTime SLADue { get; set; }
        public int WorkOrderStatusId { get; set; }
        public Nullable<int> TechnicianId { get; set; }
        public Nullable<System.DateTime> AssignedDate { get; set; }
        public Nullable<System.DateTime> CompletedDate { get; set; }
        public Nullable<int> CreatedById { get; set; }
        public string CrossStreet { get; set; }
        public Nullable<int> ResolutionCode { get; set; }
        public string ResolutionDesc { get; set; }
        public Nullable<int> AssignmentState { get; set; }
        public Nullable<int> Mechanism { get; set; }
    
        public virtual ICollection<FMWorkOrderEvent> WorkOrderEvents { get; set; }
        public virtual ICollection<FMWorkOrderImage> WorkOrderImages { get; set; }
        public virtual ICollection<FMWorkOrderPart> WorkOrderParts { get; set; }
        public virtual FMWorkOrderStatu WorkOrderStatu { get; set; }
        public virtual ICollection<FMWorkOrdersAudit> WorkOrdersAudits { get; set; }
    }
}
