//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.RBAC
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MaintenanceEntities : DbContext
    {
        public MaintenanceEntities()
            : base("name=MaintenanceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<FMPart> FMParts { get; set; }
        public DbSet<FMWorkOrderEvent> FMWorkOrderEvents { get; set; }
        public DbSet<FMWorkOrderImage> FMWorkOrderImages { get; set; }
        public DbSet<FMWorkOrderPart> FMWorkOrderParts { get; set; }
        public DbSet<FMWorkOrder> FMWorkOrders { get; set; }
        public DbSet<FMWorkOrdersAudit> FMWorkOrdersAudits { get; set; }
        public DbSet<FMWorkOrderStatu> FMWorkOrderStatus { get; set; }
    }
}
