//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.RBAC
{
    using System;
    using System.Collections.Generic;
    
    public partial class netsqlazman_StoreGroupsTable
    {
        public int StoreGroupId { get; set; }
        public int StoreId { get; set; }
        public byte[] objectSid { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string LDapQuery { get; set; }
        public byte GroupType { get; set; }
    
        public virtual netsqlazman_StoresTable netsqlazman_StoresTable { get; set; }
    }
}
