//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.RBAC
{
    using System;
    using System.Collections.Generic;
    
    public partial class netsqlazman_StoresTable
    {
        public netsqlazman_StoresTable()
        {
            this.netsqlazman_StoreGroupsTable = new HashSet<netsqlazman_StoreGroupsTable>();
            this.UserCustomerAccesses = new HashSet<UserCustomerAccess>();
        }
    
        public int StoreId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<netsqlazman_StoreGroupsTable> netsqlazman_StoreGroupsTable { get; set; }
        public virtual ICollection<UserCustomerAccess> UserCustomerAccesses { get; set; }
    }
}
