//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.RBAC
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewsContent
    {
        public int id { get; set; }
        public int ContentId { get; set; }
        public string Content { get; set; }
        public string CultureCode { get; set; }
    
        public virtual News News { get; set; }
    }
}
