//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.RBAC
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResourceEvent
    {
        public int ResourceEventsId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
        public Nullable<int> EventTypeId { get; set; }
        public string SessionID { get; set; }
        public string Controller { get; set; }
        public string Action { get; set; }
    
        public virtual ResourceEventType ResourceEventType { get; set; }
    }
}
