//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.RBAC
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfile
    {
        public UserProfile()
        {
            this.UserCustomerAccesses = new HashSet<UserCustomerAccess>();
            this.UserPasswordHistories = new HashSet<UserPasswordHistory>();
            this.UserPasswordQuestions = new HashSet<UserPasswordQuestion>();
            this.UserSettings = new HashSet<UserSetting>();
            this.webpages_Roles = new HashSet<webpages_Roles>();
        }
    
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<bool> RequirePasswordReset { get; set; }
    
        public virtual ICollection<UserCustomerAccess> UserCustomerAccesses { get; set; }
        public virtual ICollection<UserPasswordHistory> UserPasswordHistories { get; set; }
        public virtual ICollection<UserPasswordQuestion> UserPasswordQuestions { get; set; }
        public virtual ICollection<UserSetting> UserSettings { get; set; }
        public virtual Membership Membership { get; set; }
        public virtual ICollection<webpages_Roles> webpages_Roles { get; set; }
    }
}
