//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.RBAC
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_CustomerGrids
    {
        public int CustomerGridsId { get; set; }
        public int UserID { get; set; }
        public int CustomerId { get; set; }
        public string Controller { get; set; }
        public string Action { get; set; }
        public string OriginalColName { get; set; }
        public int OriginalColPos { get; set; }
    
        public virtual CustomerGrid CustomerGrid { get; set; }
    }
}
