//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duncan.PEMS.DataAccess.RBAC
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPasswordQuestion
    {
        public int UserPasswordQuestionId { get; set; }
        public int UserId { get; set; }
        public int QuestionNumber { get; set; }
        public string Question { get; set; }
        public string Answer { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
    }
}
